- .github/pull_request_template.md
- worker/src/routes/docs.ts
- worker/src/util/adoc2html.ts
- worker/src/util/books.ts
- uses book book path to resolve image src, assumes `_graphics` directory is always inside the book's directory
Test URLs:
-  Before: https://main--prisma-cloud-docs--hlxsites.hlx.page/prisma/prisma-cloud/docs/en/compute/admin-guide-pcee/access-control/rbac
- After: https://maxed-fix-images--prisma-cloud-docs--hlxsites.hlx.page/prisma/prisma-cloud/docs/en/compute/admin-guide-pcee/access-control/rbac
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/prisma/prisma-cloud/docs/en/compute/admin-guide-pcee/access-control/rbac?branch=maxed/fix-images
> fix image hrefs

- .github/workflows/preview.yaml
- bin/preview-changes.js
Related to https://github.com/hlxsites/prisma-cloud-docs-website/issues/53
Adds a new CI workflow that triggers on PRs to show preview URLs for adoc and book changes and warns about missing adoc references in books. 
Example output:
> Preview GH Action

- docs/en/cspm/use-cases/book.yml
- worker/src/util/adoc2html.ts
fix https://github.com/hlxsites/prisma-cloud-docs-website/issues/136
fix https://github.com/hlxsites/prisma-cloud-docs-website/issues/139
> various fixes

- docs/en/enterprise-edition/use-cases/book.yml
book.yml points to the wrong adoc file, so it doesn't load.
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=ian-fix-use-case
> Fix book.yml for use cases book

- bin/validate-doc-paths.js
fix https://github.com/hlxsites/prisma-cloud-docs-website/issues/148
> fix: validate-doc-paths regex

- worker/src/routes/media.ts
ref: https://github.com/hlxsites/prisma-cloud-docs-website/issues/194
> fix: workaround for incorrect mime types for some gifs

- worker/src/util/adoc2html.ts
- wrap imgs in pictures
- this shouldn't change anything in the published pages, it just makes dev mode more similar to live by more closely matching the output from Franklin
-  add `inline_image` template type
fix https://github.com/hlxsites/prisma-cloud-docs-website/issues/219
> image tweaks

- docs/en/compute-edition/30/admin-guide/alerts/aws-security-hub.adoc
- docs/en/compute-edition/31/admin-guide/alerts/aws-security-hub.adoc
removed the note that AWS Security Hub integration fails for US Gov region because we fixed it in CWP-39394; PCSUP-9241
Documented in 30.00 RN
Test URLs:
> [PCCE AG] 30 and 31 update aws-security-hub.adoc for CWP-39394

- docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2023/features-introduced-in-october-2023.adoc
HTTP/2 Rapid Reset Attack Vulnerability (CVE-2023-44487) added in october in addition to the Classic RN for Compute.
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=update-cve-rn
> [RN PCEE]  for CVE-2023-44487 update to features-introduced-in-oct

- docs/en/classic/rql-reference/rql-reference/iam-query/iam-query-conditions.adoc
Test URLs:
- Before: https://docs.prismacloud.io/en/classic/rql-reference/rql-reference/iam-query/iam-query-conditions
- After: https://docs.prismacloud.io/en/classic/rql-reference/rql-reference/iam-query/iam-query-conditions
> Fixes typo: "garnular" to "granular"

- docs/en/enterprise-edition/policy-reference/book.yml
From the [Slack conversation](https://panw-global.slack.com/archives/C01Q2LR0LF6/p1699379284872359). Removing SAST policies from `book.yml`
Modified files:
- docs/en/enterprise-edition/policy-reference/book.yml
Test URLs:
> [AppSec Policy Ref Guide] Commenting out SAST Policies

- docs/en/classic/appsec-admin-guide/book.yml
- docs/en/compute-edition/22-12/admin-guide/book.yml
- docs/en/compute-edition/30/admin-guide/book.yml
- docs/en/compute-edition/31/admin-guide/book.yml
- docs/en/enterprise-edition/content-collections/book.yml
- docs/en/enterprise-edition/policy-reference/book.yml
Fix all book.yml files so that dir topics are properly named.
Clicking on some dirs (with the expand/collapse control) in the left nav causes some load weirdness that confuses users due to issues in the underlying book.yml
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=ian-fix-dir-topics2
> Fix dir topics

- docs/en/enterprise-edition/policy-reference/sast-policies/java-policies/sast-java-policy-index.adoc
- docs/en/enterprise-edition/policy-reference/sast-policies/javascript-policies/sast-javascript-policy-index.adoc
- docs/en/enterprise-edition/policy-reference/sast-policies/python-policies/sast-python-policy-index.adoc
Resorted Java, JavaScript and Python policies according to severity (critical to low) with alphabetical subsorting within a severity.
> Resorted Sast Policies jb

- docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/ensure-storage-for-critical-data-are-encrypted-with-customer-managed-key.adoc
The suggested key permissions will fail as written due to Terraform expecting a specific case for the actions:
│ Error: expected key_permissions.0 to be one of ["Get" "List" "Update" "Create" "Import" "Delete" "Recover" "Backup" "Restore" "Decrypt" "Encrypt" "UnwrapKey" "WrapKey" "Verify" "Sign" "Purge" "Release" "Rotate" "GetRotationPolicy" "SetRotationPolicy"], got get
│ 
│   with azurerm_key_vault_access_policy.client,
│   on main.tf line 23, in resource "azurerm_key_vault_access_policy" "client":
│   23:   key_permissions    = ["get", "create", "delete", "list", "restore", "recover", "unwrapkey", "wrapkey", "purge", "encrypt", "decrypt", "sign", "verify"]
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed …
> changing casing so Terraform works

- docs/en/classic/compute-admin-guide/compliance/detect-secrets.adoc
- docs/en/compute-edition/31/admin-guide/compliance/detect-secrets.adoc
- docs/en/compute-edition/32/admin-guide/compliance/detect-secrets.adoc
- docs/en/enterprise-edition/content-collections/runtime-security/compliance/operations/detect-secrets.adoc
The ID's need to be swapped for container and host secret scanning:
@jenjoe22 
Test URLs:
> fixing incorrect compliance id

- docs/.vscode/settings.json
- docs/en/enterprise-edition/content-collections/dashboards/create-and-manage-dashboards.adoc
- docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-january-2024.adoc
> 1.2 rn update

- docs/en/compute-edition/32/admin-guide/access-control/open-policy-agent.adoc
ValidatingWebookConfiguration changed to ValidatingWebhookConfiguration
Test URLs:
> Fix typos in open-policy-agent.adoc

- docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-azurerepos.adoc
- docs/en/enterprise-edition/content-collections/application-security/get-started/non-default-branch-scan.adoc
Jira ticket: https://redlock.atlassian.net/browse/RLP-131847
Test URLs:
> [AppSec] Non-default branch scanning is only available under the new pricing model

- docs/en/enterprise-edition/content-collections/application-security/ides/connect-jetbrains.adoc
- docs/en/enterprise-edition/content-collections/application-security/ides/connect-vscode.adoc
Jira ticket 👍 https://redlock.atlassian.net/browse/RLP-133492
Test URLs:
> [AppSec] Added permissions required to integrate Prisma Cloud plugin with IDEs

- docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-github-server.adoc
- docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-gitlab-selfmanaged.adoc
Jira ticket :https://redlock.atlassian.net/browse/RLP-133730
Test URLs:
> [AppSec] Added port 443 limitation to GitHub and GitLab enterprise integrations

- worker/src/util/adoc2html.ts
Fix issue with custom section ids being rendered as para text instead of being properly applied as the secion/div id.
Fix [hlxsites/prisma-cloud-docs-website#205](https://github.com/hlxsites/prisma-cloud-docs-website/issues/205)
> fix: custom section ids

- docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-bitbucket.adoc
- docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-github-server.adoc
Jira ticket: https://redlock.atlassian.net/browse/RLP-134714
Test URLs:
> [AppSec] Rephrased "repo" permissions required for GitHub Server integration

- docs/en/classic/compute-admin-guide/agentless-scanning/agentless-scanning.adoc
- docs/en/compute-edition/32/admin-guide/agentless-scanning/agentless-scanning.adoc
- docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/agentless-scanning.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=cwp-50822
> [Runtime Security]Remove cost implication note in agentless scanning

- worker/src/util/adoc2html.ts
Currently, the worker's converter for images doesn't support the `imagesdir` attribute. We'd like to be able to set a value in `book.yml` and then have it propagate across all image macros in the book.
AsciiDoctor user manual for `imagesdir`: https://docs.asciidoctor.org/asciidoc/latest/macros/images-directory/
Effectively, `getImageUri()` combines the value in `imagesdir`  (if there is one) along with the image macro target ( `image::<TARGET>`) to get a value that can be used directly in `href` in the HTML5 `image` tag.
> [Worker] Add support for the imagesdir attr

- docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-azurerepos.adoc
- docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-bitbucket.adoc
- docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-github-server.adoc
- docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-gitlab-selfmanaged.adoc
- docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-gitlab.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-31662
Test URLs:
> [AppSec] Added repo permissions to vcs integrations excepting GitHub Cloud

- docs/en/compute-edition/32/rn/release-information/release-notes-32-04.adoc
- docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-compute-release-information/features-introduced-in-compute-march-2024.adoc
Fix: This is patch update for blurb CWP-56798 addressed in #505 and #506 
Test URLs:
> [Runtime Security] Patch for blurb CWP-56798

- docs/en/enterprise-edition/content-collections/application-security/risk-management/monitor-and-manage-code-build/suppress-code-issues.adoc
Jira ticket: https://redlock.atlassian.net/browse/RLP-131308
Added an inline dev suppress heading and fixed a  link after reordering IDE docs
Test URLs:
> [AppSec] Modify Suppression documentation

- docs/en/enterprise-edition/content-collections/application-security/manage-network-tunnel/deploy-transporter-docker.adoc
- docs/en/enterprise-edition/content-collections/application-security/manage-network-tunnel/deploy-transporter-helmcharts.adoc
Jira ticket https://redlock.atlassian.net/browse/RLP-136561
Test URLs:
> [AppSec] Add log capability for Helm charts in Transporter docs

- docs/en/enterprise-edition/content-collections/application-security/risk-management/monitor-and-manage-code-build/secrets-scanning.adoc
Jira ticket: https://redlock.atlassian.net/browse/RLP-136754
Test URLs:
> [CAS ]Added supported file types and entropy analysis to Secrets docs

- docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-systems/ci-cd-systems.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-33109
Added GitLab CI and Azure Pipelines to the list of sy=upported systems for CI/CD Systems. In addition removed the limitation for BB Data Center, adding this system to the list of supported systems
Test URLs:
> [CAS] CI/CD System docs - Added support for Azure Pipelines, GitLab CI and BB Data Center  

- docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-bitbucket-server.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-33388
Test URLs:
> [CAS] BB Data Center Added caveat to tokens, requiring admin permissions for CI/CD scans

- docs/en/enterprise-edition/content-collections/application-security/risk-management/monitor-and-manage-code-build/software-composition-analysis/sca-troubleshoot.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-33470
Test URLs:
> [CAS] Removed SCA unsupported error message for "Package lock JSON v3 

- docs/en/enterprise-edition/content-collections/application-security/risk-management/monitor-and-manage-code-build/software-composition-analysis/sca-troubleshoot.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-33470
Removed and requested to restore at @maryarmely's request 7thMay 2024
Test URLs:
> [CAS] SCA Error messages: Restore Package lock JSON v3 not supported error msg

- docs/en/enterprise-edition/content-collections/governance/custom-build-policies/code-editor.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-33624
Test URLs:
> [Governance] Added supported scan types for Attribute Operators in Code Editors

- docs/en/enterprise-edition/content-collections/governance/custom-build-policies/code-editor.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-33624
Test URLs:
> [Governance] Code Editors  - Custom Build Policies:  Removed a column for supported scan types for operators 

- docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-azurerepos.adoc
- docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-bitbucket-server.adoc
- docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-bitbucket.adoc
- docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-github-server.adoc
- docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-gitlab-selfmanaged.adoc
- docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-gitlab.adoc
…. Added project admin permissions to azure integration for webhooks
Jira ticket: https://redlock.atlassian.net/browse/BCE-33648
Test URLs:
> [CAS] Added organization owner permissions to all VCS integrations except GitHub SaaS

- docs/en/compute-edition/32/admin-guide/audit/review-debug-logs.adoc
- docs/en/enterprise-edition/content-collections/runtime-security/audit/review-debug-logs.adoc
Fix: Patch for #626 
Test URLs:
> [Runtime Security] Fix Syntax for CWP-55880

- docs/en/enterprise-edition/content-collections/application-security/risk-management/monitor-and-manage-code-build/software-composition-analysis/sca-troubleshoot.adoc
This format is now supported.
Jira ticket: https://redlock.atlassian.net/browse/BCE-33820
Test URLs:
> [CAS] Removed JavaScript Lockfile v3 Error Msg from Documentation

- docs/en/enterprise-edition/content-collections/application-security/ides/ides.adoc
- docs/en/enterprise-edition/content-collections/application-security/supported-technologies.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-34817
Prisma Cloud now offers support for scanning Ansible, an Infrastructure as Code (IaC) framework
Test URLs:
> [CAS] Ansible scan support for IaC misconfigurations 

- docs/en/enterprise-edition/content-collections/application-security/supported-technologies.adoc
Jira ticket: (https://redlock.atlassian.net/browse/BCE-35263)
Test URLs:
> [CAS] Removed redundant list of supported SCA package managers in Supported Technologies 

- docs/en/enterprise-edition/content-collections/data-security-posture-management/api-documentation/authenticate-and-call-your-first-api.adoc
- docs/en/enterprise-edition/content-collections/data-security-posture-management/troubleshooting/gcp-monitoring-issues.adoc
Fix empty pages
For content-collections/data-security-posture-management/api-documentation/authenticate-and-call-your-first-api.adoc:
* Fix broken table syntax
* Fix mispelled Gdoc file name
> [Dig docs] Fix empty pages

- docs/en/compute-edition/32/admin-guide/agentless-scanning/onboard-accounts/configure-aws.adoc
- docs/en/compute-edition/32/admin-guide/deployment-patterns/performance-planning.adoc
- docs/en/compute-edition/33/admin-guide/agentless-scanning/onboard-accounts/configure-aws.adoc
- docs/en/compute-edition/33/admin-guide/deployment-patterns/performance-planning.adoc
- docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/configure-accounts/configure-aws.adoc
Fix: CWP-62082, CWP-61360
Test URLs:
> Boot Volume Encryption

- docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
- docs/en/enterprise-edition/rn/known-issues/known-issues.adoc
> [Known Issues] Add 2 new KIs

- docs/en/enterprise-edition/content-collections/administration/network-security/container-network-exposure/container-network-exposure-overview.adoc
- docs/en/enterprise-edition/content-collections/administration/network-security/container-network-exposure/deploy-satellite.adoc
- docs/en/enterprise-edition/content-collections/administration/network-security/container-network-exposure/satellite-prerequisites.adoc
- docs/en/enterprise-edition/content-collections/administration/network-security/container-network-exposure/troubleshoot-container-network-exposure.adoc
- docs/en/enterprise-edition/content-collections/administration/network-security/investigate-network-exposure-on-prisma-cloud.adoc
> [Cloud Sec] Container Updates

- docs/en/enterprise-edition/content-collections/governance/custom-build-policies/code-editor.adoc
Jira: https://jira-dc.paloaltonetworks.com/browse/BCE-41418
Test URLs:
> [Governance] Code editor  - add limitation for "NOT" logical operator  

- docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-checkov.adoc
> Update Checkov permissions

- docs/en/compute-edition/32/admin-guide/waas/waas-api-discovery.adoc
- docs/en/compute-edition/33/admin-guide/agentless-scanning/onboard-accounts/onboard-oci.adoc
- docs/en/compute-edition/33/admin-guide/tools/twistcli.adoc
- docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/configure-accounts/onboard-oci.adoc
- docs/en/enterprise-edition/content-collections/runtime-security/runtime-defense/runtime-audits.adoc
- docs/en/enterprise-edition/content-collections/runtime-security/tools/twistcli.adoc
- docs/en/enterprise-edition/content-collections/runtime-security/waas/scan-api-definition.adoc
> runtime-pascal-update-2-AG

- docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-gcp/prerequisites-to-onboard-gcp.adoc
- docs/en/enterprise-edition/rn/book.yml
- docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
- docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-2024.adoc
- docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-december-2024.adoc
- docs/en/enterprise-edition/rn/prisma-cloud-release-info/prisma-cloud-release-info.adoc
> [CSPM RN] - 24.12.1 - Nov 29th publish

- docs/en/enterprise-edition/content-collections/governance/custom-build-policies/code-editor.adoc
- docs/en/enterprise-edition/content-collections/governance/custom-build-policies/custom-build-policies.adoc
- docs/en/enterprise-edition/content-collections/governance/custom-build-policies/custom-build-policy-examples.adoc
- docs/en/enterprise-edition/content-collections/governance/custom-build-policies/visual-editor.adoc
Jira:https://jira-dc.paloaltonetworks.com/browse/BCE-35801
Test URLs:
> [CAS] Added ARM framework to custom build policies

- docs/en/enterprise-edition/rn/limited-ga-features-prisma-cloud/limited-ga-features-prisma-cloud.adoc
- docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-december-2024.adoc
> [24.12.1 RN] Action Plans & Secrets

- docs/en/enterprise-edition/content-collections/search-and-investigate/permissions-queries/permissions-query-attributes.adoc
> permission-query-update

- docs/en/compute-edition/31/admin-guide/install/deploy-defender/host/host.adoc
- docs/en/compute-edition/32/admin-guide/install/deploy-defender/host/host.adoc
- docs/en/compute-edition/33/admin-guide/install/deploy-defender/host/host.adoc
- docs/en/enterprise-edition/content-collections/runtime-security/install/deploy-defender/container/container.adoc
- docs/en/enterprise-edition/content-collections/runtime-security/install/deploy-defender/kubernetes/kubernetes.adoc
> Updates for CWP-62517

- docs/en/compute-edition/31/admin-guide/agentless-scanning/onboard-accounts/configure-azure.adoc
- docs/en/compute-edition/32/admin-guide/agentless-scanning/onboard-accounts/configure-azure.adoc
- docs/en/compute-edition/33/admin-guide/agentless-scanning/onboard-accounts/configure-azure.adoc
- docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/configure-accounts/configure-azure.adoc
> [Backlog] CWP-58130

- docs/en/enterprise-edition/policy-reference/aws-policies/aws-general-policies/aws-general-policies.adoc
- docs/en/enterprise-edition/policy-reference/aws-policies/aws-general-policies/bc-aws-381.adoc
- docs/en/enterprise-edition/policy-reference/aws-policies/aws-general-policies/bc-aws-383.adoc
- docs/en/enterprise-edition/policy-reference/aws-policies/aws-networking-policies/aws-networking-policies.adoc
- docs/en/enterprise-edition/policy-reference/aws-policies/aws-networking-policies/bc-aws-378.adoc
- docs/en/enterprise-edition/policy-reference/aws-policies/aws-networking-policies/bc-aws-382.adoc
- docs/en/enterprise-edition/policy-reference/azure-policies/azure-networking-policies/azure-networking-policies.adoc
- docs/en/enterprise-edition/policy-reference/azure-policies/azure-networking-policies/bc-azure-2-55.adoc
- docs/en/enterprise-edition/policy-reference/azure-policies/azure-networking-policies/bc-azure-245.adoc
- docs/en/enterprise-edition/policy-reference/azure-policies/azure-networking-policies/bc-azure-246.adoc
- docs/en/enterprise-edition/policy-reference/book.yml
> Adding docs for December build policies

- docs/en/compute-edition/32/admin-guide/runtime-defense/runtime-defense-containers.adoc
> PCSUP-10244

- docs/en/enterprise-edition/content-collections/search-and-investigate/network-queries/network-config-query-attributes.adoc
- docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-may-2024.adoc
> [Cloud Security] PCSUP-22206

- docs/en/enterprise-edition/policy-reference/aws-policies/aws-iam-policies/aws-iam-policies.adoc
- docs/en/enterprise-edition/policy-reference/aws-policies/aws-iam-policies/iam-358.adoc
- docs/en/enterprise-edition/policy-reference/azure-policies/azure-iam-policies/azr-iam-249.adoc
- docs/en/enterprise-edition/policy-reference/azure-policies/azure-iam-policies/azure-iam-policies.adoc
- docs/en/enterprise-edition/policy-reference/book.yml
- docs/en/enterprise-edition/policy-reference/google-cloud-policies/google-cloud-iam-policies/gcp-iam-125.adoc
- docs/en/enterprise-edition/policy-reference/google-cloud-policies/google-cloud-iam-policies/google-cloud-iam-policies.adoc
> Add docs for OIDC checks

- .github/pull_request_template.md
- README.md
- bin/generate-sitemaps.js
- bin/preview-changes.js
- preview/README.md
- wrangler.toml
ref: https://github.com/hlxsites/prisma-cloud-docs-website/pull/250
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=v5
> feat: upgrade to v5

- docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/third-party-ingestion/sarif-ingestion.adoc
- docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/third-party-ingestion/veracode-ingestion.adoc
Jira ticket:https://jira-dc.paloaltonetworks.com/browse/BCE-46714
Fix allow list link in Veracode and removed + operator
Test URLs:
> CAS Third Party Ingestion Fixes

- docs/en/enterprise-edition/content-collections/application-security/ides/ides.adoc
Jira ticket: https://jira-dc.paloaltonetworks.com/browse/BCE-48913
Test URLs:
> [CAS] IDE Added limitation to user names in file paths

- docs/en/enterprise-edition/content-collections/application-security/risk-management/monitor-and-manage-code-build/software-composition-analysis/sca-troubleshoot.adoc
Jira ticket: https://jira-dc.paloaltonetworks.com/browse/BCE-50128
Test URLs:
> [CAS] Update supported frameworks for missing-lock files under SCA troubleshooting
