hlxsites/prisma-cloud-docs

.stylelintrc.json, package-lock.json, package.json
Test URLs:
- Before: https://main--prisma-cloud-docs--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/admin-guide-pcee/welcome/welcome
- After: https://maxed-ci--prisma-cloud-docs--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/admin-guide-pcee/welcome/welcome
=> fix: test deploy

worker/src/util/adoc2html.ts
- fix nested ordered lists
- fix where text prefixing list was excluded
- add block for `procedure` ordered lists
=> converter bugs

docs/en/compute/30-xx/admin-guide/install/system-requirements.adoc
=> [Test] Update Compute AG: system requirements

docs/en/compute/ops-guide/phases/learn.adoc
=> [Test] Update Ops Guide

docs/en/compute/ops-guide/phases/learn.adoc
=> Test updating file

.github/workflows/deploy.yaml, .github/workflows/publish-sitemaps.yaml, .releaserc.cjs
=> chore: update sitemaps on each commit

bin/generate-sitemaps.js
=> chore: exclude invalid files from sitemaps

docs/en/compute/ops-guide/book.yml, docs/en/compute/ops-guide/getting-started/test-sitemap2.adoc
=> Add file to book

docs/en/compute/21-08/admin-guide/book.yml, docs/en/compute/22-01/admin-guide/book.yml, docs/en/compute/22-06/admin-guide/book.yml, docs/en/compute/22-12/admin-guide/book.yml, docs/en/compute/30-xx/admin-guide/book.yml, docs/en/compute/pcee/admin-guide/book.yml
=> Fix admin guide book titles

package-lock.json, package.json, worker/src/util/adoc2html.ts
Fix https://github.com/hlxsites/prisma-cloud-docs-website/issues/110
=> fix: wrap lists in div

bin/preview-changes.js
=> fix: make preview comment sticky and urls shorter

worker/src/util/adoc2html.ts
fixes https://github.com/hlxsites/prisma-cloud-docs-website/issues/127
=> fix: handle query strings and hashes in xrefs

docs/en/compute/pcee/admin-guide/book.yml, docs/en/compute/pcee/admin-guide/welcome/test-headings.adoc
Add article with all section heading levels in order
=> Test styling for section headings

worker/src/util/adoc2html.ts
fix https://github.com/hlxsites/prisma-cloud-docs-website/issues/135
=> para admonition

.gitignore, docs/en/cspm/policy-reference/.vscode/settings.json
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=ian-del-vscode
=> Ignore .vscode directories

docs/en/enterprise-edition/content-collections/book.yml
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=ian-add-darwin-bookyml
=> Add darwin docs book.yml

docs/en/enterprise-edition/content-collections/book.yml
Quote topic titles with question marks.
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=ian-fix-bookyml
=> Quote special chars in book.yml

docs/en/enterprise-edition/content-collections/book.yml
Fix indentation issue
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=ian-fix-book
=> Fix book.yml

docs/en/enterprise-edition/content-collections/book.yml
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=ian-fix
=> Fix indentation in book.yml

bin/generate-sitemaps.js, docs/sitemaps/sitemap-jp.xml
fix https://github.com/hlxsites/prisma-cloud-docs-website/issues/164
=> fix: better sitemap generation, fix sitemap bug

bin/batch-publish.js, worker/src/util/adoc2html.ts
fix https://github.com/hlxsites/prisma-cloud-docs-website/issues/168
=> fix: undefined xref titles

worker/src/util/adoc2html.ts
fix https://github.com/hlxsites/prisma-cloud-docs-website/issues/171
=> fix: more selective section metadata

docs/en/classic/rql-reference/rql-reference/iam-query/iam-query-attributes.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=ian-update-rql-ref
=> Update classic/rql-reference - 231015

docs/en/classic/appsec-admin-guide/get-started/add-pre-receive-hooks.adoc, docs/en/classic/appsec-admin-guide/get-started/code-repositories-policy-management/code-repositories-policy-management.adoc, docs/en/classic/appsec-admin-guide/get-started/code-repositories-policy-management/custom-build-policy-examples.adoc, docs/en/classic/appsec-admin-guide/get-started/connect-your-repositories/ci-cd-runs/add-checkov.adoc, docs/en/classic/appsec-admin-guide/get-started/drift-detection.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=ian-update-appsec-ag
=> Update Classic App Sec AG - 231015

docs/en/classic/rql-reference/rql-reference/config-query/config-query-attributes.adoc, docs/en/classic/rql-reference/rql-reference/config-query/config-query-examples.adoc, docs/en/classic/rql-reference/rql-reference/event-query/event-query-attributes.adoc, docs/en/classic/rql-reference/rql-reference/event-query/event-query-examples.adoc, docs/en/classic/rql-reference/rql-reference/iam-query/iam-query-attributes.adoc, docs/en/classic/rql-reference/rql-reference/operators.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=ian-rm-draft-comment
=> [RQL Ref] Remove draft comments

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc, docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-cspm-release-information/features-introduced-in-april-2023.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-cspm-release-information/features-introduced-in-august-2023.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-cspm-release-information/features-introduced-in-february-2023.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-cspm-release-information/features-introduced-in-january-2023.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-cspm-release-information/features-introduced-in-july-2023.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-cspm-release-information/features-introduced-in-june-2023.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-cspm-release-information/features-introduced-in-march-2023.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-cspm-release-information/features-introduced-in-may-2023.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-cspm-release-information/features-introduced-in-october-2023.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-cspm-release-information/features-introduced-in-september-2023.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2023/features-introduced-in-october-2023.adoc
=> Rn replacements

docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-code-security-release-information/features-introduced-in-code-security-august-2023.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-compute-release-information/features-introduced-in-compute-august-2023.adoc
=> Rn fix for merge conflict

docs/en/enterprise-edition/content-collections/runtime-security/pcee-vs-pcce.adoc, docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/registry-scanning/configure-registry-scanning.adoc
=> [Runtime Security]Image fixes

docs/en/classic/cspm-admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-aws/aws-apis-ingested-by-prisma-cloud.adoc, docs/en/classic/cspm-admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-gcp/gcp-apis-ingested-by-prisma-cloud.adoc, docs/en/classic/cspm-admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-your-alibaba-account/alibaba-apis-ingested-by-prisma-cloud.adoc, docs/en/classic/cspm-admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-your-azure-account/microsoft-azure-apis-ingested-by-prisma-cloud.adoc, docs/en/classic/cspm-admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-your-oci-account/oci-apis-ingested-by-prisma-cloud.adoc, docs/en/classic/cspm-admin-guide/manage-prisma-cloud-administrators/prisma-cloud-admin-permissions.adoc, docs/en/enterprise-edition/content-collections/connect/connect-code-and-build-providers.adoc, docs/en/enterprise-edition/content-collections/connect/connect-image-registries.adoc, docs/en/enterprise-edition/content-collections/connect/deploy-defenders.adoc, docs/en/enterprise-edition/content-collections/search-and-investigate/asset-queries/asset-queries.adoc
=> updated sheets path, fixed xrefs

docs/en/classic/cspm-admin-guide/get-started-with-prisma-cloud/access-the-prisma-cloud-api.adoc, docs/en/classic/cspm-admin-guide/manage-prisma-cloud-administrators/get-started-with-oidc-sso/get-started-with-oidc-sso.adoc, docs/en/classic/cspm-admin-guide/prisma-cloud-iam-security/remediate-alerts-for-iam-security.adoc, docs/en/enterprise-edition/content-collections/administration/configure-data-security/monitor-data-security-scan/data-security-settings.adoc, docs/en/enterprise-edition/content-collections/administration/setup-sso-integration-on-prisma-cloud/get-started-with-oidc-sso/get-started-with-oidc-sso.adoc, docs/en/enterprise-edition/content-collections/get-started/access-keys.adoc, docs/en/enterprise-edition/content-collections/get-started/prisma-cloud-platform.adoc
=> Troubleshooting

docs/en/enterprise-edition/content-collections/book.yml
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=rcaballeromx:compliance-book-fix
=> [Compliance] Fix name in book

docs/en/enterprise-edition/rn/prisma-cloud-release-info/prisma-cloud-release-info.adoc
=> [RN] Update prisma-cloud-release-info

docs/en/classic/compute-admin-guide/install/system-requirements.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/system-requirements.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=spreadsheets
=> [Runtime Security]Fix spreadsheets in System Requirements

docs/en/classic/compute-admin-guide/welcome/saas-maintenance.adoc, docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/vulnerability-management-policies.adoc
=> Xref fixes

docs/en/enterprise-edition/content-collections/book.yml, docs/en/enterprise-edition/content-collections/runtime-security/compliance/operations/detect-secrets.adoc, docs/en/enterprise-edition/content-collections/runtime-security/runtime-security-collection.yml
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=secret-detection
=> [Runtime Security]Fix missing Compliance updates

docs/en/enterprise-edition/content-collections/governance/custom-build-policies/visual-editor.adoc
=> Modify the table in procedure

docs/en/compute-edition/31/rn/release-information/release-notes-31-02-update2.adoc
=> [Compute RN]: Add SHA-256

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
known issue for CWP-52736
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=Pubs-MV-patch-1
=> [PCCE 31.xx RN]Update known-fixed-issues.adoc

docs/en/classic/cspm-admin-guide/get-started-with-prisma-cloud/get-started-with-prisma-cloud.adoc, docs/en/enterprise-edition/content-collections/administration/configure-data-security/monitor-data-security-scan/exposure-evaluation.adoc, docs/en/enterprise-edition/content-collections/administration/configure-data-security/monitor-data-security-scan/mask-sensitive-data-on-prisma-cloud.adoc, docs/en/enterprise-edition/content-collections/administration/create-manage-account-groups.adoc, docs/en/enterprise-edition/content-collections/administration/trusted-ip-addresses-on-prisma-cloud.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/add-private-registries.adoc, docs/en/enterprise-edition/content-collections/dashboards/dashboards-code-to-cloud.adoc, docs/en/enterprise-edition/content-collections/get-started/welcome-to-prisma-cloud.adoc, docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
=> C2C updates + QA cleanup

docs/en/classic/compute-admin-guide/welcome/security-assurance-policy.adoc, docs/en/compute-edition/31/admin-guide/welcome/security-assurance-policy.adoc, docs/en/enterprise-edition/content-collections/runtime-security/runtime-security-components/licensing/security-assurance-policy.adoc
=> [PCWE and PCEE] Update security-assurance-policy for PCSUP-18967

docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/connect-code-and-build-providers.adoc
=> [AppSec]- Fixed broken image in Connect code & build providers

docs/en/enterprise-edition/content-collections/application-security/visibility/repositories.adoc, docs/en/enterprise-edition/content-collections/application-security/visibility/sbom.adoc, docs/en/enterprise-edition/content-collections/application-security/visibility/technologies/jenkins-plugins.adoc, docs/en/enterprise-edition/content-collections/application-security/visibility/technologies/pipeline-tools.adoc, docs/en/enterprise-edition/content-collections/application-security/visibility/technologies/technologies.adoc, docs/en/enterprise-edition/content-collections/application-security/visibility/technologies/technology-overview.adoc, docs/en/enterprise-edition/content-collections/application-security/visibility/technologies/vcs-third-parties.adoc, docs/en/enterprise-edition/content-collections/application-security/visibility/visibility.adoc
=> Small changes

docs/en/compute-edition/31/rn/book.yml, docs/en/compute-edition/31/rn/book_point_release.yml, docs/en/compute-edition/31/rn/release-information/release-notes-31-02-update2-build-31-02-137.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/prisma-cloud-release-info.adoc
=> [Newton Update 2 Build 31-02-137]: PCCE RN

docs/en/classic/compute-admin-guide/tools/twistcli-scan-iac.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/connect-azure-account.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/connect-azure-active-directory.adoc
=> Azure updates

docs/en/enterprise-edition/content-collections/application-security/familiarize-application-security.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/add-private-registries.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-aws-codebuild.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-checkov.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-circleci.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-github-actions.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-jenkins.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-systems/add-circleci-cicd-system.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-systems/add-jenkins-cicd-system.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-azurerepos.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-bitbucket-server.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-bitbucket.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-github-server.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-github.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-gitlab-selfmanaged.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-gitlab.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/code-repositories.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/manage-network-tunnel/deploy-transporter-docker.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/manage-network-tunnel/deploy-transporter-helmcharts.adoc
=> modifies helm chart instructions - housekeeping

docs/en/enterprise-edition/content-collections/application-security/get-started/add-pre-receive-hooks.adoc
=> [App-Sec] Modified Pre-receive hooks

docs/en/enterprise-edition/content-collections/application-security/get-started/add-pre-receive-hooks.adoc, docs/en/enterprise-edition/content-collections/application-security/visibility/repositories.adoc, docs/en/enterprise-edition/content-collections/application-security/visibility/visibility.adoc
=> Test bookmark appgraph

docs/en/classic/compute-admin-guide/configure/permissions.adoc, docs/en/compute-edition/30/admin-guide/configure/permissions.adoc, docs/en/compute-edition/31/admin-guide/configure/permissions.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=permissions-classic
=> [Compute AG]Fix permissions table for Classic

docs/en/enterprise-edition/content-collections/dashboards/dashboards-code-to-cloud.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=<c-to-c-fix>
=> removing SAST as it's not available yet

docs/en/compute-edition/31/admin-guide/install/deploy-defender/orchestrator/install-gke-autopilot.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/deploy-defender/kubernetes/gke-autopilot.adoc
=> [Runtime Security]: Update GKE Autopilot Defender command

docs/en/enterprise-edition/content-collections/administration/configure-iam-security/enable-iam-security.adoc
=> update for 116255

docs/en/classic/cspm-admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-aws/configure-audit-logs.adoc, docs/en/enterprise-edition/content-collections/connect/collection-connect.yml, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-aws/configure-audit-logs.adoc, docs/en/enterprise-edition/content-collections/connect/connect.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=23-11-1-aws-eventbridge-update
=> [AWS] RLP-113615 AWS EventBridge updates

docs/en/classic/cspm-admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-aws/configure-audit-logs.adoc, docs/en/classic/cspm-admin-guide/prisma-cloud-data-security/monitor-data-security-scan-prisma-cloud/monitor-data-security-scan-prisma-cloud.adoc, docs/en/classic/cspm-admin-guide/prisma-cloud-network-security/create-a-network-policy.adoc, docs/en/classic/cspm-admin-guide/prisma-cloud-network-security/prisma-cloud-network-security.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=fix-classic-cspm-pcds-undefined
=> updated undefined xrefs

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-compute-release-information/features-introduced-in-compute-november-2023.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/prisma-cloud-release-info.adoc
=> [Runtime Security RN]: Newton Update 3 PCEE

docs/en/enterprise-edition/rn/book.yml
=> [Newton Update 3 RN]: Update book.yml

docs/en/compute-edition/30/admin-guide/install/deploy-defender/app-embedded/deploy-app-embedded-defender-gcr.adoc
=> [Runtime Security]: Add deploy defender in GCR file

docs/en/classic/rql-reference/rql-reference/operators.adoc
Test URLs:
- After: https://live--prisma-cloud-docs--hlxsites.hlx.page/
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=rql-cross-account-joins
=> minor text updates

docs/en/classic/compute-admin-guide/agentless-scanning/agentless-scanning-modes.adoc, docs/en/compute-edition/31/admin-guide/agentless-scanning/agentless-scanning-modes.adoc, docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/agentless-scanning-modes.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=scan-duration
=> [Runtime Security]Update Agentless Scans duration

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
=> Update look-ahead for ONeal

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
=> LA late updates

docs/en/enterprise-edition/content-collections/administration/prisma-cloud-admin-permissions.adoc
Test URLs:
- After: https://live--prisma-cloud-docs--hlxsites.hlx.page/
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=updt-pc-perms-appsec
=> update permissions to include AppSec

docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2023/features-introduced-in-december-2023.adoc
=> remove two apis

docs/en/enterprise-edition/content-collections/dashboards/dashboards-vulnerabilities.adoc
=> [Dashboard - UVE]: Vulnerabilities count updates

docs/en/compute-edition/31/admin-guide/install/deploy-defender/serverless/auto-defend-serverless.adoc, docs/en/compute-edition/31/admin-guide/technology-overviews/radar.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/deploy-defender/serverless/auto-defend-serverless.adoc, docs/en/enterprise-edition/content-collections/runtime-security/runtime-security-components/radar.adoc
=> [CWP-42711]: Update info on auto-defend serverless functions

docs/en/classic/appsec-admin-guide/get-started/drift-detection.adoc, docs/en/enterprise-edition/content-collections/application-security/risk-management/monitor-and-manage-code-build/drift-detection.adoc
The troubleshooting section was referencing Prisma Cloud's permissions, but it should be the permissions in AWS, Azure or GCP.
Fixed a few other items.
=> Fix troubleshooting

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
=> Compute RN PCEE updates

docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/troubleshoot-vulnerability-detection.adoc
=> [Vuln mgmt]: Fix table formatting

docs/en/compute-edition/32/admin-guide/book.yml, docs/en/compute-edition/32/rn/book.yml
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=ian-pcee-oneal-books
=> Add Compute Edition 32 book.yml files

docs/en/enterprise-edition/content-collections/administration/configure-iam-security/integrate-prisma-cloud-with-idp-services.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/connect-azure-account.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/microsoft-azure-apis-ingested-by-prisma-cloud.adoc
=> Azure fixes

docs/en/compute-edition/32/admin-guide/compliance/trusted-images.adoc, docs/en/enterprise-edition/content-collections/runtime-security/compliance/operations/trusted-images.adoc
=> [Compute-CWP-46051]: Update the note on trusted image status

docs/en/compute-edition/31/admin-guide/install/system-requirements.adoc, docs/en/compute-edition/32/admin-guide/install/system-requirements.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/system-requirements.adoc
=> [CWP-49167-49461] Remove CNNS note

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc, docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
Aish,
I've added Giri's requested updates with the exception of https://redlock.atlassian.net/browse/RLP-114555. If you hear back regarding the updates needed, please go ahead and add along with any clean-up needed. Feel free to merge if it looks good to you and Giri. Thanks.
Test URLs:
=> RN Updates

docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-azurerepos.adoc
See Jira:https://redlock.atlassian.net/browse/RLP-125429
=> Fixed typo: replaced Bitbucket with Azure in step 1.2

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=oneal-update-1-look-ahead
=> [Runtime Security] O'Neal Update 1 Look Ahead

docs/en/compute-edition/32/admin-guide/install/system-requirements.adoc
[CWP-54649](https://redlock.atlassian.net/browse/CWP-54649)
Test URLs:
=> Update system-requirements.adoc links to the O'Neal sheet

docs/en/enterprise-edition/policy-reference/aws-policies/aws-iam-policies/ensure-the-aws-execution-role-arn-and-task-role-arn-are-different-in-ecs-task-definitions.adoc
Fix [Checkov 5850](https://github.com/bridgecrewio/checkov/issues/5850)
=> Add content for CKV_AWS_249

docs/api/_topic_map.yml, docs/api/descriptions/policies/vulnerability_base_images_id_delete.md, docs/api/descriptions/tags/tag_cve_post.md
https://redlock.atlassian.net/browse/CWP-53808
Test URLs:
=> Updates to CWPP API Ref for O'Neal Update1

docs/api/descriptions/collections/post.md
Updated for CWP-51321
Test URLs:
=> Update post.md  for CWP-51321

docs/en/classic/cspm-admin-guide/prisma-cloud-iam-security/cloud-identity-inventory.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/connect-azure-account.adoc, docs/en/enterprise-edition/content-collections/get-started/adoption-advisor.adoc
=> PCSUP-18383 update

docs/en/compute-edition/32/rn/book.yml, docs/en/compute-edition/32/rn/book_point_release.yml, docs/en/compute-edition/32/rn/release-information/release-notes-32-00.adoc, docs/en/compute-edition/32/rn/release-information/release-notes-32-01.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=32-1-pcce-rn
=> [Runtime Security PCCE] O'Neal Update 1 Release Notes

docs/en/enterprise-edition/rn/book.yml, docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc, docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-compute-release-information/features-introduced-in-compute-january-2024.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=32-1-pcee-rn
=> [Runtime Security PCEE] O'Neal Update 1 Release Notes

docs/api/_build/src/enrich_spec_saas.py, docs/api/_build/src/enrich_spec_sh.py, docs/api/_build/src/gen_supported_spec_sh.py, docs/api/_topic_map.yml, docs/api/descriptions/coderepos-ci/post_resolve.md
=> Changed the ref paths in compute spec files

docs/api/descriptions/tags/tag_cve_post.md
=> Fixed the numbered list formatting

docs/en/classic/compute-admin-guide/install/system-requirements.adoc, docs/en/compute-edition/22-12/admin-guide/install/system-requirements.adoc, docs/en/compute-edition/30/admin-guide/install/system-requirements.adoc, docs/en/compute-edition/31/admin-guide/install/system-requirements.adoc, docs/en/compute-edition/32/admin-guide/install/system-requirements.adoc
Fix CWP-53445
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=ian/CWP-53445
=> [Runtime Security] Fix anchor syntax

docs/en/enterprise-edition/policy-reference/book.yml, docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/azure-repo-cicd-pipeline-policies/azure-repo-cicd-pipeline-policies.adoc, docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/bitbucket-cicd-pipeline-policies/bitbucket-cicd-pipeline-policies.adoc, docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/circleci-cicd-pipeline-policies/circleci-cicd-pipeline-policies.adoc, docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/github-cicd-pipeline-policies/github-cicd-pipeline-policies.adoc, docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/gitlab-cicd-pipeline-policies/gitlab-cicd-pipeline-policies.adoc
=> Ap sec jb policies

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=32-2-look-ahead
=> [Runtime Security PCEE] O'Neal Update 2 Look Ahead

docs/en/classic/compute-admin-guide/install/deploy-defender/host/windows-host.adoc, docs/en/compute-edition/32/admin-guide/install/deploy-defender/host/windows-host.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/deploy-defender/host/windows-host.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=windows-table
=> [Runtime Security]Fix broken table

docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/set-an-expiration-date-on-all-keys.adoc
This policy has nothing to do with managed disks and should be changed.
Test URLs:
=> fix policy name

docs/en/enterprise-edition/content-collections/dashboards/dashboards-compliance.adoc
=> Compliance dashboard

docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/connect-azure-account.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/connect-azure-subscription.adoc
=> RLP-126205

docs/en/enterprise-edition/content-collections/administration/prisma-cloud-licenses.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-aws/update-onboarded-aws-accnt-to-org.adoc, docs/en/enterprise-edition/content-collections/runtime-security/runtime-security-components/licensing/licensing.adoc, docs/en/enterprise-edition/content-collections/runtime-security/runtime-security.adoc, docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/vulnerability-explorer.adoc
=> oneal1 fixes

docs/en/enterprise-edition/rn/book.yml, docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc, docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-compute-release-information/features-introduced-in-compute-february-2024.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=32-1-pcee-rn
=> [Runtime Security PCEE] O'Neal Update 2 Release Notes

docs/en/compute-edition/32/rn/book.yml, docs/en/compute-edition/32/rn/book_point_release.yml, docs/en/compute-edition/32/rn/release-information/release-notes-32-02.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=32-2-pcee-rn
=> [Runtime Security PCCE] O'Neal Update 2 Release Notes

docs/en/classic/compute-admin-guide/compliance/custom-compliance-checks.adoc
=> CWP-52985 - Custom Compliance checks

docs/en/classic/cspm-admin-guide/manage-prisma-cloud-administrators/add-a-resource-list-on-prisma-cloud.adoc, docs/en/classic/cspm-admin-guide/prisma-cloud-dashboards/asset-inventory.adoc, docs/en/enterprise-edition/content-collections/administration/add-a-resource-list-on-prisma-cloud.adoc, docs/en/enterprise-edition/content-collections/cloud-and-software-inventory/asset-inventory.adoc, docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=doc-rn-updates-RLP-127621
=> Doc-rn-updates-RLP-127621

docs/en/classic/compute-admin-guide/configure/permissions.adoc, docs/en/compute-edition/32/admin-guide/configure/permissions.adoc, docs/en/enterprise-edition/content-collections/runtime-security/configure/permissions.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=cwp-51897
=> [Runtime Security]Fix permissions page navigation

docs/en/compute-edition/32/admin-guide/install/system-requirements.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/system-requirements.adoc
Fix PCSUP-19427
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=istio-limit
=> [Runtime Security]Clarify missing Istio containers

docs/en/compute-edition/32/admin-guide/access-control/open-policy-agent.adoc
=> Fix typo in open-policy-agent.adoc

docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-terraform-run-tasks.adoc
=> [APP_SEC] Modified TF Cloud Run Tasks title

docs/en/classic/appsec-admin-guide/get-started/connect-your-repositories/ci-cd-runs/add-github-actions.adoc
=> Fix misspelling

docs/en/compute-edition/public-sector/book.yml
added one entry to book.yaml in prisma-cloud-docs/docs/en/compute-edition/public-sector/book.yml
=> Added Public Sector v31-01-123.adoc

docs/en/classic/cspm-admin-guide/connect-your-cloud-platform-to-prisma-cloud/cloud-service-provider-regions-on-prisma-cloud.adoc, docs/en/classic/cspm-admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-gcp/prerequisites-to-onboard-gcp.adoc, docs/en/enterprise-edition/content-collections/administration/subscribe-to-cdem.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/cloud-service-provider-regions-on-prisma-cloud.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-gcp/prerequisites-to-onboard-gcp.adoc
This PR contains updates based on 
- [RLP-127972](https://redlock.atlassian.net/browse/RLP-127972)
- [RLP-129451](https://redlock.atlassian.net/browse/RLP-129451)
- GCP Ingestions for 24.2.1
Test URLs:
=> [CSPM Collections] - Updates to CDEM and connect collections. 

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
=> [Runtime Security][PCEE] Look Ahead - O'Neal Update 3

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
As suggested by engineering and PM
Test URLs:
=> O'Neal update 3 LA updated the note for CWP-44666 and removed CWP-41449

docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-terraform-enterprise-run-tasks.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-terraform-run-tasks.adoc
=> fixed link

docs/api/_build/src/compute-build.py, docs/api/_build/src/enrich_spec_saas.py, docs/api/_build/src/enrich_spec_sh.py, docs/api/_build/src/gen_supported_spec_saas.py, docs/api/_build/src/gen_supported_spec_sh.py, docs/api/_build/src/sort_tags.py, docs/api/_build/src/update_spec_file.py
These changes automates the manual steps of executing 6 python files and creating directories before publsihing compute 
changes.
Test URLs:
=> compute_publishing_script_changes

docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-azurerepos.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-bitbucket-server.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-github-server.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-github.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-gitlab-selfmanaged.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-gitlab.adoc
Jira ticket: 
https://redlock.atlassian.net/browse/PCSUP-21193
Test URLs:
=> App sec fib bbserverdoc

docs/en/enterprise-edition/content-collections/application-security/risk-management/monitor-and-manage-code-build/enforcement.adoc
Jira: https://redlock.atlassian.net/browse/RLP-131312
Test URLs:
=> [App-Sec] Enforcement - Fix format issue for optional access

docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-qualys.adoc
Update integrate-prisma-cloud-with-qualys.adoc
Test URLs:
=> Fix draft comment issues based on Slack request

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
=> {Draft] Revised as plans for migration to AWS have been dropped

docs/en/enterprise-edition/content-collections/book.yml, docs/en/enterprise-edition/content-collections/get-started/prisma-cloud-dspm-assets.adoc
=> dspm assets classification

docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-azurerepos.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-bitbucket-server.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-bitbucket.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-github-server.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-github.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-gitlab-selfmanaged.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-gitlab.adoc
Jira ticket https://redlock.atlassian.net/browse/RLP-130381
Test URLs:
=> [AppSec] VCS Permissions

docs/en/enterprise-edition/content-collections/get-started/prisma-cloud-dspm-assets.adoc
=> dspm asset list updated

docs/en/enterprise-edition/content-collections/alerts/saved-views.adoc, docs/en/enterprise-edition/content-collections/book.yml, docs/en/enterprise-edition/content-collections/governance/manage-prisma-cloud-policies.adoc
=> 2.2-ag-updates

docs/en/enterprise-edition/policy-reference/book.yml
Delete stray conflict markers in the book.yml. Whoever resolved these conflicts will need to come back and reevaluate that all desired content is properly included and published. This is just a quick fix to fix broken previews for the rest of the system/ team.
=> [Enterprise Edition][Policy Reference] Fix book.yml

docs/en/classic/compute-admin-guide/agentless-scanning/agentless-scanning-modes.adoc, docs/en/compute-edition/32/admin-guide/agentless-scanning/agentless-scanning-modes.adoc, docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/agentless-scanning-modes.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=cwp-55524
=> [Runtime Security][CWP-55524] Update scanning modes to include Azure

docs/en/classic/cspm-admin-guide/get-started-with-prisma-cloud/enable-access-prisma-cloud-console.adoc, docs/en/enterprise-edition/rn/limited-ga-features-prisma-cloud/limited-ga-features-prisma-cloud.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-february-2024.adoc
=> cns updates

docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-february-2024.adoc
=> CNS-9541 f/b updates

docs/en/classic/cspm-admin-guide/prisma-cloud-iam-security/enable-iam-security.adoc, docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
=> broken link fix

docs/en/classic/compute-admin-guide/configure/permissions.adoc, docs/en/compute-edition/32/admin-guide/configure/permissions.adoc, docs/en/enterprise-edition/content-collections/runtime-security/configure/permissions.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=encryption-link
=> [Runtime Security] Move list of AWS permissions needed

docs/api/descriptions/vms/stop_post.md
=> API description changes for CWP-55307 

docs/en/compute-edition/32/rn/release-information/release-notes-32-03.adoc
=> CWP-51234-changes

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
=> RLP-133444

docs/en/classic/compute-admin-guide/configure/permissions.adoc, docs/en/classic/cspm-admin-guide/prisma-cloud-policies/manage-prisma-cloud-policies.adoc, docs/en/compute-edition/22-12/admin-guide/configure/permissions.adoc, docs/en/compute-edition/30/admin-guide/configure/permissions.adoc, docs/en/compute-edition/31/admin-guide/configure/permissions.adoc, docs/en/compute-edition/32/admin-guide/configure/permissions.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/microsoft-azure-apis-ingested-by-prisma-cloud.adoc, docs/en/enterprise-edition/content-collections/dashboards/dashboards-code-to-cloud.adoc, docs/en/enterprise-edition/content-collections/runtime-security/configure/permissions.adoc
=> azure-perms+copy-fix

docs/en/compute-edition/32/rn/book.yml, docs/en/compute-edition/32/rn/book_point_release.yml, docs/en/compute-edition/32/rn/release-information/release-notes-32-03.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=runtime-32-3-PCCE-RN
=> [Runtime Security][PCCE RN]Update build number after hotfix

docs/en/classic/appsec-admin-guide/get-started/code-repositories-policy-management/code-editor.adoc, docs/en/enterprise-edition/content-collections/governance/custom-build-policies/code-editor.adoc
Add `intersects` and `not_intersects` that are both now supported
=> Add intersects

docs/en/compute-edition/32/rn/release-information/release-notes-32-00.adoc
JIRA: https://redlock.atlassian.net/browse/PCSUP-21922
Test URLs:
=> [Runtime Security] PCSUP-21922

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
=> [Runtime Security] LA-PCEE O'Neal Update 4

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
=> Removing the note for Go package level scans (CWP-56709) as it was included in the 32.03 RN

docs/en/compute-edition/32/rn/release-information/release-notes-32-01.adoc, docs/en/compute-edition/32/rn/release-information/release-notes-32-02.adoc
This is a hotfix and is not tracked by a JIRA ticket
Test URLs:
=> [Runtime Security] Hotfix to RN- O'Neal

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
=> Removed the note for Go package as it was included in 32.03 RN

docs/en/compute-edition/32/rn/release-information/release-notes-32-03.adoc
=> Adding more detail to the note about improved Go scans (CWP-42824)

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
=> Removed the duplicate for CWP-55859 and CWP-56784

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
=> Minor fixes

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
=> Forcing page refresh

docs/en/enterprise-edition/content-collections/search-and-investigate/network-queries/network-config-query-attributes.adoc
=> note added for effective.action

docs/en/enterprise-edition/content-collections/search-and-investigate/network-queries/network-config-query-attributes.adoc
=> [Network Config Query] Fix note

docs/en/compute-edition/32/rn/release-information/release-notes-32-00.adoc, docs/en/compute-edition/32/rn/release-information/release-notes-32-01.adoc, docs/en/compute-edition/32/rn/release-information/release-notes-32-02.adoc, docs/en/compute-edition/32/rn/release-information/release-notes-32-03.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=rn-upgrade-blurb
=> [Runtime Security]Update Defender upgrade blurb releases

docs/en/enterprise-edition/content-collections/application-security/risk-management/monitor-and-manage-code-build/monitor-code-build-issues.adoc
Jira ticket: [RLP-134934](https://redlock.atlassian.net/browse/RLP-134934)
Test URLs:
=> [AppSec] Monitor Code Build Issues: Removed unrelated "xref" 

docs/en/classic/compute-admin-guide/configure/permissions.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/connect-azure-account.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/microsoft-azure-apis-ingested-by-prisma-cloud.adoc, docs/en/enterprise-edition/content-collections/dashboards/collection-dashboards.yml, docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/configure-accounts/configure-azure.adoc, docs/en/enterprise-edition/content-collections/runtime-security/configure/permissions.adoc, docs/en/enterprise-edition/rn/get-help/get-help.adoc
=> PCSUP Fixes

docs/en/enterprise-edition/content-collections/application-security/ides/connect-jetbrains.adoc, docs/en/enterprise-edition/content-collections/application-security/ides/connect-vscode.adoc
Jira ticket  https://redlock.atlassian.net/browse/RLP-135118
Test URLs:
=> [AppSec ] Fix links in IDE docs

docs/jp/enterprise-edition/content-collections/book.yml
Add book.yml for JP > Enterprise Edition > Content Collections
=> Add book.yml to main for jp content

docs/en/enterprise-edition/policy-reference/book.yml, docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/azure-repo-cicd-pipeline-policies/azure-repo-cicd-pipeline-policies.adoc, docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/azure-repo-cicd-pipeline-policies/azure-repo-insecure-def-secret-var.adoc, docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/azure-repo-cicd-pipeline-policies/azure-repo-npm-download-no-commit-hash-ref.adoc, docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/azure-repo-cicd-pipeline-policies/azure-repo-npm-project-unused-dependencies.adoc, docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/azure-repo-cicd-pipeline-policies/azure-repo-repo-not-dismiss-pr-approval-db.adoc, docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/bitbucket-cicd-pipeline-policies/bb-npm-download-no-commit-hash-ref.adoc, docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/bitbucket-cicd-pipeline-policies/bb-repo-npm-project-unused-dependencies.adoc, docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/bitbucket-cicd-pipeline-policies/bitbucket-cicd-pipeline-policies.adoc, docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/github-cicd-pipeline-policies/gh-repo-npm-download-no-commit-hash-ref.adoc, docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/github-cicd-pipeline-policies/gh-repo-npm-project-unused-dependencies.adoc, docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/github-cicd-pipeline-policies/github-cicd-pipeline-policies.adoc, docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/gitlab-cicd-pipeline-policies/gitlab-cicd-pipeline-policies.adoc, docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/gitlab-cicd-pipeline-policies/gl-repo-npm-download-no-commit-hash-ref.adoc, docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/gitlab-cicd-pipeline-policies/gl-repo-npm-project-unused-dependencies.adoc
Jira:https://redlock.atlassian.net/browse/RLP-133759
Test URLs:
=> CI/CD Risk Policies 02/24

docs/en/classic/compute-admin-guide/agentless-scanning/onboard-accounts/configure-aws.adoc, docs/en/classic/compute-admin-guide/agentless-scanning/onboard-accounts/configure-azure.adoc, docs/en/classic/compute-admin-guide/agentless-scanning/onboard-accounts/configure-gcp.adoc, docs/en/compute-edition/32/admin-guide/agentless-scanning/onboard-accounts/configure-aws.adoc, docs/en/compute-edition/32/admin-guide/agentless-scanning/onboard-accounts/configure-azure.adoc, docs/en/compute-edition/32/admin-guide/agentless-scanning/onboard-accounts/configure-gcp.adoc, docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/configure-accounts/configure-aws.adoc, docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/configure-accounts/configure-azure.adoc, docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/configure-accounts/configure-gcp.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=agentless-fixes
=> [Runtime Security]Agentless small fixes

docs/en/enterprise-edition/content-collections/book.yml, docs/en/enterprise-edition/content-collections/connect/collection-connect.yml, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-gcp/onboard-gcp-workspace.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-gcp/onboard-gcp.adoc
=> connect google workspace

docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrations-feature-support.adoc, docs/en/enterprise-edition/content-collections/administration/create-custom-permission-groups.adoc, docs/en/enterprise-edition/content-collections/administration/create-manage-account-groups.adoc, docs/en/enterprise-edition/content-collections/administration/prisma-cloud-admin-permissions.adoc, docs/en/enterprise-edition/content-collections/search-and-investigate/network-queries/network-config-queries.adoc
=> RLP-134037 fix

docs/en/enterprise-edition/content-collections/get-started/prisma-cloud-dspm-assets.adoc
=> update based on PCDTUS-100

docs/en/compute-edition/32/rn/book.yml, docs/en/compute-edition/32/rn/book_point_release.yml, docs/en/compute-edition/32/rn/release-information/release-notes-32-04.adoc
=> O'Neal-Update4-PCCE-RN

docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-march-2024.adoc
=> post-32.04 rn fixes

docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-march-2024.adoc
=> Minor updates to features-introduced-in-march-2024.adoc

docs/en/compute-edition/32/rn/release-information/release-notes-32-04.adoc, docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-compute-release-information/features-introduced-in-compute-march-2024.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-march-2024.adoc
This branch is a patch fix for the #505 and #506. 
Jira ticket references in the  commit. 
Test URLs:
=> [Runtime Security] O'Neal Update 4 -Patch update

docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-march-2024.adoc
=> rn 24.3.2 fixes

docs/en/compute-edition/32/rn/book.yml, docs/en/compute-edition/32/rn/release-information/release-notes-32-04.adoc
This is a patch fix for #505 
Test URLs:
=> [Runtime Security] PCCE-Add Missed Addressed Issues

docs/en/enterprise-edition/use-cases/book.yml
=> fixed typo in book.yml

docs/en/enterprise-edition/content-collections/alerts/create-an-alert-rule-cloud-infrastructure.adoc
Test URLs:
- Worker: https://prisma-cloud-docs-production.adobeaem.workers.dev/?branch=pcsup-21253
=> [Alerts][pcsup-21253]Add maximum value accepted for alert triggering

docs/en/enterprise-edition/content-collections/application-security/risk-management/monitor-and-manage-code-build/suppress-code-issues.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-31170
Test URLs:
=> [AppSec] Suppressions - Added Guidelines 

docs/en/classic/compute-admin-guide/configure/permissions.adoc, docs/en/classic/compute-admin-guide/waas/waas-advanced-settings.adoc, docs/en/enterprise-edition/content-collections/dashboards/dashboards-get-started.adoc, docs/en/enterprise-edition/content-collections/runtime-security/configure/permissions.adoc, docs/en/enterprise-edition/content-collections/runtime-security/waas/waas-advanced-settings.adoc
=> PCSUP-22237

docs/en/enterprise-edition/content-collections/get-started/welcome-to-prisma-cloud.adoc
=> licensing-purchased credits increase

docs/en/enterprise-edition/content-collections/application-security/collection-application-security.yml, docs/en/enterprise-edition/content-collections/book.yml
Jira ticket: https://redlock.atlassian.net/browse/RLP-134280
Test URLs:
=> [CAS] Renamed the bb server in the hierarchy to bb data center/server

docs/en/compute-edition/31/rn/book.yml, docs/en/compute-edition/31/rn/release-information/release-notes-31-03-update3-build-31-03-109.adoc
=> Newton Update 3 Hotfix 31.03.109 RN

docs/en/enterprise-edition/content-collections/application-security/manage-network-tunnel/deploy-transporter-docker.adoc, docs/en/enterprise-edition/content-collections/application-security/manage-network-tunnel/deploy-transporter-helmcharts.adoc, docs/en/enterprise-edition/content-collections/application-security/manage-network-tunnel/manage-network-tunnel.adoc, docs/en/enterprise-edition/content-collections/application-security/manage-network-tunnel/transporter-connectivity-overview.adoc
Jira ticket: https://redlock.atlassian.net/browse/PCSUP-16769
Test URLs:
=> [AppSec] Transporter update-added whitelist wss and qualified 'name' content

docs/en/classic/compute-admin-guide/alerts/webhook.adoc
JIRA Ticket: https://redlock.atlassian.net/browse/CWP-56018
Changes made to:
- Classic Edition
Test URLs:
=> [Runtime Security] CWP-56018

docs/en/enterprise-edition/content-collections/get-started/prisma-cloud-dspm-assets.adoc
=> Added SaaS in DSPM

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
=> [Runtime Security] LA O'Neal Update 5

docs/en/enterprise-edition/content-collections/reports/create-and-manage-reports.adoc
=> Added note in Alerts Reports

docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-april-2024.adoc
=> 4-2-link-update

docs/en/classic/compute-admin-guide/continuous-integration/code-repo-scanning.adoc, docs/en/classic/compute-admin-guide/vulnerability-management/code-repo-scanning.adoc, docs/en/compute-edition/32/admin-guide/continuous-integration/code-repo-scanning.adoc, docs/en/compute-edition/32/admin-guide/vulnerability-management/code-repo-scanning.adoc
Fix #179 - This is a patch update in PCCE for the changes in PCEE. 
Test URLs:
=> [Runtime Security] [AG] CWP-36043 Patch

docs/en/classic/compute-admin-guide/upgrade/upgrade-defender-single-container.adoc, docs/en/compute-edition/32/admin-guide/upgrade/frag-upgrade-defender-single-container.adoc, docs/en/enterprise-edition/content-collections/runtime-security/upgrade/frag-upgrade-defender-single-container.adoc
Fix: Broken pages in the docs.
JIRA: https://redlock.atlassian.net/browse/CWP-56983
Test URLs:
=> [Runtime Security] AG- CWP-56983

docs/en/classic/compute-admin-guide/alerts/jira.adoc, docs/en/compute-edition/32/admin-guide/alerts/jira.adoc
JIRA: https://redlock.atlassian.net/browse/CWP-54807
Test URLs:
=> [Runtime Security AG] CWP-54807

docs/en/compute-edition/30/admin-guide/upgrade/upgrade-defender-single-container.adoc, docs/en/compute-edition/31/admin-guide/upgrade/upgrade-defender-single-container.adoc, docs/en/compute-edition/32/admin-guide/upgrade/upgrade-defender-single-container.adoc, docs/en/enterprise-edition/content-collections/runtime-security/collection-runtime-security.yml, docs/en/enterprise-edition/content-collections/runtime-security/upgrade/upgrade-defender-single-container.adoc
=> [Runtime Security] Patch for CWP-56983

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
=> Fixed a broken link

docs/en/enterprise-edition/policy-reference/aws-policies/aws-iam-policies/bc-aws-355.adoc, docs/en/enterprise-edition/policy-reference/aws-policies/aws-iam-policies/bc-aws-356.adoc
=> Fix docs for CKV_AWS_355 and CKV_AWS_356

docs/en/enterprise-edition/content-collections/get-started/adoption-advisor.adoc
=> Update adoption-advisor.adoc Typo fix

docs/en/enterprise-edition/content-collections/search-and-investigate/permissions-queries/permissions-query-attributes.adoc
=> remove erroneous closing square brackets

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc, docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-may-2024.adoc
Fix: Release Notes for PCEE O'Neal Update 5. https://redlock.atlassian.net/browse/CWP-56900
Test URLs:
=> [Runtime Security] PCEE-RN-O'Neal Update 5

docs/en/compute-edition/32/rn/book.yml, docs/en/compute-edition/32/rn/book_point_release.yml, docs/en/compute-edition/32/rn/release-information/release-notes-32-05.adoc
Fix : Release Notes for PCCE O'Neal Update 5. https://redlock.atlassian.net/browse/CWP-56900
Test URLs:
=> [Runtime Security] PCCE-RN-O'Neal Update 5

docs/en/enterprise-edition/content-collections/book.yml
Jira ticket: https://redlock.atlassian.net/browse/BCE-32899
The topic was deleted inadvertently while fixing an issue with a PR
Test URLs:
=> [CAS] Added 'fix code issues' to book yml

docs/en/enterprise-edition/content-collections/administration/prisma-cloud-licenses.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-33046
Test URLs:
=> [Administration] Added how to locate Prisma ID to Licensing 

docs/en/enterprise-edition/content-collections/search-and-investigate/explore-data.adoc
=> [Cloud Sec] Expore Data - Node content fixes

docs/en/classic/compute-admin-guide/install/deploy-defender/host/auto-defend-host.adoc, docs/en/classic/compute-admin-guide/waas/waas-app-firewall.adoc, docs/en/compute-edition/32/admin-guide/install/deploy-defender/host/auto-defend-host.adoc, docs/en/compute-edition/32/admin-guide/install/system-requirements.adoc, docs/en/compute-edition/32/admin-guide/waas/waas-app-firewall.adoc
=> PCCE AG Changes

docs/en/compute-edition/32/admin-guide/agentless-scanning/agentless-scanning.adoc, docs/en/compute-edition/32/admin-guide/cloud-service-providers/cloud-service-providers.adoc, docs/en/compute-edition/32/admin-guide/compliance/cis-benchmarks.adoc, docs/en/compute-edition/32/admin-guide/configure/permissions.adoc, docs/en/compute-edition/32/admin-guide/install/deploy-defender/orchestrator/orchestrator.adoc, docs/en/compute-edition/32/admin-guide/install/system-requirements.adoc, docs/en/compute-edition/32/admin-guide/vulnerability-management/scan-reports.adoc, docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/agentless-scanning.adoc, docs/en/enterprise-edition/content-collections/runtime-security/cloud-service-providers/cloud-service-providers.adoc, docs/en/enterprise-edition/content-collections/runtime-security/compliance/visibility/cis-benchmarks.adoc, docs/en/enterprise-edition/content-collections/runtime-security/configure/permissions.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/deploy-defender/app-embedded/app-embedded.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/deploy-defender/host/auto-defend-host.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/deploy-defender/kubernetes/kubernetes.adoc, docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/scan-reports.adoc, docs/en/enterprise-edition/content-collections/runtime-security/waas/waas-app-firewall.adoc
Update the fix for https://redlock.atlassian.net/browse/CWP-57409
Test URLs:
=> PCEE AG Changes

docs/en/enterprise-edition/content-collections/governance/custom-build-policies/code-editor.adoc
Jira ticket https://redlock.atlassian.net/browse/BCE-33730
Test URLs:
=> [Governance] Fixed operator table on Code Editor

docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-february-2024.adoc
Fix : Add missed RN blurb for O'Neal update 3. https://redlock.atlassian.net/browse/CWP-56709
Test URLs:
=> [Runtime Security] Update 3 - Patch RN

docs/en/compute-edition/32/admin-guide/agentless-scanning/agentless-scanning.adoc, docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/agentless-scanning.adoc
Changed the formatting for a note in the Scan Statuses section, as per comment by Omri Cohen.
=> Review comments for CWP-57628.

docs/en/enterprise-edition/content-collections/dashboards/create-and-manage-dashboards.adoc, docs/en/enterprise-edition/content-collections/dashboards/dashboards-command-center.adoc, docs/en/enterprise-edition/content-collections/dashboards/dashboards-vulnerabilities.adoc
=> PCEE-AG fixes

docs/en/compute-edition/32/admin-guide/install/system-requirements.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/system-requirements.adoc
=> Update for CWP-54499

docs/en/classic/cspm-admin-guide/manage-prisma-cloud-administrators/adoption-advisor.adoc, docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-microsoft-teams.adoc, docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-splunk.adoc, docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-webhooks.adoc
=> AG updates based on RLP-129856 hotfix

docs/en/compute-edition/32/admin-guide/audit/logging.adoc, docs/en/compute-edition/32/admin-guide/audit/review-debug-logs.adoc, docs/en/compute-edition/32/admin-guide/book.yml, docs/en/enterprise-edition/content-collections/runtime-security/audit/logging.adoc, docs/en/enterprise-edition/content-collections/runtime-security/audit/review-debug-logs.adoc
Fix : https://redlock.atlassian.net/browse/CWP-55880
Test URLs:
=> [Runtime Security] AG - CWP-55880

docs/en/enterprise-edition/content-collections/application-security/risk-management/monitor-and-manage-code-build/software-composition-analysis/license-compliance-in-sca.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-32566
Test URLs:
=> [CAS] Fix links from license to license policies and enforcement

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
Fix: https://redlock.atlassian.net/browse/CWP-58179
Test URLs:
=> [Runtime Security] LA - O'Neal Update 6 (Pascal)

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
=> [LA 24.6.1] LM updates

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
=> Fixed formatting

docs/en/enterprise-edition/content-collections/runtime-security/configure/permissions.adoc
=> Rlp-142260-updates

docs/en/compute-edition/22-12/admin-guide/install/system-requirements.adoc, docs/en/compute-edition/30/admin-guide/install/system-requirements.adoc, docs/en/compute-edition/31/admin-guide/install/system-requirements.adoc, docs/en/compute-edition/32/admin-guide/install/system-requirements.adoc, docs/en/enterprise-edition/content-collections/administration/add-a-resource-list-on-prisma-cloud.adoc, docs/en/enterprise-edition/content-collections/dashboards/create-and-manage-dashboards.adoc, docs/en/enterprise-edition/content-collections/get-started/console-prerequisites.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/system-requirements.adoc
This PR includes updates for:
- https://redlock.atlassian.net/browse/RLP-139616
- Broken Link
- Slack feedback updates
=> RLP-139616 updates

docs/en/enterprise-edition/content-collections/cloud-and-software-inventory/cdem-unmanaged-assets-inventory.adoc, docs/en/enterprise-edition/content-collections/dashboards/dashboards-discovery-exposure-management.adoc
This PR contains updates for -
[[CDEM Documentation] Update documentation for Regex snooze feature](https://redlock.atlassian.net/browse/RLP-140581)
[[CDEM Documentation] - Update Vulnerability sidecar & Top Risks widget](https://redlock.atlassian.net/browse/RLP-132742)
--
</body>
</html>
Test URLs:
[RLP-140581](https://redlock.atlassian.net/browse/RLP-140581)
=> [CSPM Content Collections] for 24.6.1 by AN.

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-june-2024.adoc
=> Compute 32-06 changes

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
=> [6.1] Fixed Issue

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-june-2024.adoc
=> PM review updates

docs/api/_build/src/gen_supported_spec_saas.py, docs/api/_build/src/update_spec_file.py, docs/api/_topic_map.yml, docs/api/descriptions/images/get.md, docs/api/descriptions/sbom/download_ci_images_get.md, docs/api/descriptions/sbom/download_ci_serverless_get.md, docs/api/descriptions/sbom/download_hosts_get.md, docs/api/descriptions/sbom/download_images_get.md, docs/api/descriptions/sbom/download_registry_get.md, docs/api/descriptions/sbom/download_serverless_get.md, docs/api/descriptions/sbom/download_vms_get.md, docs/api/descriptions/sbom/sbom_intro.md, docs/api/descriptions/settings/registry_post.md, docs/en/compute-edition/32/admin-guide/configure/disaster-recovery.adoc, docs/en/compute-edition/32/rn/release-information/release-notes-32-03.adoc
Changes as part of https://redlock.atlassian.net/browse/CWP-57953, https://redlock.atlassian.net/browse/CWP-58891, https://redlock.atlassian.net/browse/CWP-58807 tickets.
Test URLs:
=> Oneal6 changes - Part1

docs/en/enterprise-edition/content-collections/application-security/risk-management/monitor-and-manage-code-build/secrets-scanning.adoc, docs/en/enterprise-edition/content-collections/governance/custom-build-policies/custom-build-policy-examples.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-34595
Test URLs:
=> [Governance] Add secret example to custom build policy examples  

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-june-2024.adoc
=> RN-changes-4thjune

docs/en/enterprise-edition/content-collections/search-and-investigate/permissions-queries/permissions-query-attributes.adoc
=> pcsup-23365

docs/en/compute-edition/32/admin-guide/vulnerability-management/vuln-explorer.adoc, docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/vulnerability-explorer.adoc
Fix: Add supported languages in Vulnerability Explorer
JIRA: https://redlock.atlassian.net/browse/CWP-57083
Test URLs:
=> [Runtime Security] AG CWP-57083

docs/en/compute-edition/32/admin-guide/audit/logging.adoc, docs/en/enterprise-edition/content-collections/runtime-security/audit/logging.adoc
Fix: JIRA: https://redlock.atlassian.net/browse/CWP-55880
Subtask where the fix is being tracked: https://redlock.atlassian.net/browse/CWP-59034
Test URLs:
=> [Runtime Security] CWP-55880 (59034)

docs/en/compute-edition/32/admin-guide/waas/deploy-waas/deployment-vpc-mirroring.adoc, docs/en/enterprise-edition/content-collections/runtime-security/waas/deploy-waas/vpc-mirroring.adoc
Fix : Add content to help download CFT template. Changes in both PCEE and PCCE. 
JIRA: https://redlock.atlassian.net/browse/CWP-54508
Test URLs:
=> [Runtime Security] CWP- 54508

docs/en/compute-edition/32/admin-guide/install/deploy-defender/orchestrator/install-kubernetes-cri.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/deploy-defender/kubernetes/kubernetes-cri.adoc
Fix: JIRA: https://redlock.atlassian.net/browse/CWP-58131
Test URLs:
=> [Runtime Security] AG CWP-58131

docs/en/compute-edition/32/rn/release-information/release-notes-32-01.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-january-2024.adoc
Fix: Related to #302 #304 
JIRA: https://redlock.atlassian.net/browse/CWP-58231
Test URLs:
=> [Runtime Security] CWP-58231

docs/en/enterprise-edition/content-collections/runtime-security/configure/rule-ordering-pattern-matching.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/cluster-context.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/deploy-defender/kubernetes/gke.adoc, docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/prisma-cloud-vulnerability-feed.adoc
=> Added content for CWP-56782, CWP-56571, CWP-59133, CWP-58772

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
=> RLP-143404 Known Issue

docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-may-2024.adoc
Fix: JIRA: https://redlock.atlassian.net/browse/CWP-55308
Test URLs:
=> [Runtime Security] CWP-55308

docs/en/enterprise-edition/content-collections/runtime-security/configure/certificates.adoc
=> changed right angular bracket to HTML code for table formatting

docs/en/enterprise-edition/content-collections/runtime-security/configure/certificates.adoc
=> adjusted column widths

docs/en/enterprise-edition/policy-reference/aws-policies/aws-logging-policies/bc-aws-logging-30.adoc, docs/en/enterprise-edition/policy-reference/book.yml, docs/en/enterprise-edition/policy-reference/google-cloud-policies/google-cloud-kubernetes-policies/bc-google-cloud-123.adoc, docs/en/enterprise-edition/policy-reference/google-cloud-policies/google-cloud-kubernetes-policies/google-cloud-kubernetes-policies.adoc, docs/en/enterprise-edition/policy-reference/google-cloud-policies/google-cloud-networking-policies/bc-google-cloud-124.adoc, docs/en/enterprise-edition/policy-reference/google-cloud-policies/google-cloud-networking-policies/google-cloud-networking-policies.adoc, docs/en/enterprise-edition/policy-reference/supply-chain-policies/terraform-policies/ensure-terraform-module-sources-use-git-url-with-commit-hash-revision.adoc, docs/en/enterprise-edition/policy-reference/supply-chain-policies/terraform-policies/ensure-terraform-module-sources-use-tag.adoc, docs/en/enterprise-edition/policy-reference/supply-chain-policies/terraform-policies/terraform-policies.adoc
=> Add 3 build policies

docs/en/enterprise-edition/policy-reference/book.yml, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-109.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-110.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-111.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-112.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/secrets-policy-index.adoc
=> Add 4 secrets

docs/en/compute-edition/32/rn/book.yml, docs/en/compute-edition/32/rn/book_point_release.yml, docs/en/compute-edition/32/rn/release-information/known-issues-32.adoc, docs/en/compute-edition/32/rn/release-information/release-notes-32-06.adoc
=> Runtime oneal 32 6 pcce ag

docs/en/enterprise-edition/content-collections/dashboards/create-and-manage-dashboards.adoc
=> [Cloud Security] Manage Widgets update for SFDC

docs/en/enterprise-edition/content-collections/dashboards/create-and-manage-dashboards.adoc
=> [Manage Widgets] Fixed Note Formatting

docs/en/compute-edition/32/rn/release-information/release-notes-32-05.adoc
Fix : PCCE part of the fix.
JIRA: https://redlock.atlassian.net/browse/CWP-55308
Test URLs:
=> [Runtime Security] Quick Fix for RN

docs/en/enterprise-edition/rn/prisma-cloud-release-info/prisma-cloud-release-info.adoc
=> Update text to .06

docs/en/enterprise-edition/rn/limited-ga-features-prisma-cloud/limited-ga-features-prisma-cloud.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/prisma-cloud-release-info.adoc
=> LGA Update

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
=> Removed the known issue for CWP-59104

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
=> RLP-142813 update

docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-gcp/onboard-gcp-workspace.adoc
=> Doc enhancement for PCSUP-23439 (RLP-143685)

docs/en/enterprise-edition/rn/.vscode/settings.json, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-june-2024.adoc
=> 6-1-RN-fix

docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-systems/add-jenkins-cicd-system.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-35695
Test URLs:
=> [CAS] Modified Jenkins Server integration guide

docs/en/enterprise-edition/content-collections/cloud-and-software-inventory/cdem-unmanaged-assets-inventory.adoc
This PR contains cc updates for [https://redlock.atlassian.net/browse/RLP-143231](RLP-143231) 
Test URLs:
=> [CSPM Content Collections] - CDEM Network Flowlog filter update for 24.7.1

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
=> Added 3 API Ingestions

docs/en/enterprise-edition/content-collections/alerts/create-an-alert-rule-cloud-infrastructure.adoc, docs/en/enterprise-edition/content-collections/search-and-investigate/permissions-queries/permissions-query-attributes.adoc
=> Quick fixes

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
=> Revised Look Ahead for 32.07

docs/en/enterprise-edition/rn/limited-ga-features-prisma-cloud/limited-ga-features-prisma-cloud.adoc, docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
=> Post RN requests for 7-2

.vscode/settings.json, docs/en/enterprise-edition/content-collections/application-security/risk-management/monitor-and-manage-code-build/software-composition-analysis/software-composition-analysis.adoc, docs/en/enterprise-edition/content-collections/application-security/risk-management/risk-indicators.adoc
(https://redlock.atlassian.net/browse/BCE-36529)
Test URLs:
=> [CAS] Added Runtime Vulnerabilities to SCA docs

docs/en/enterprise-edition/content-collections/application-security/visibility/repositories.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-35368
ease always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Test URLs:
=> [CAS] Repositories: limited CI/CD scans on user repos

docs/en/enterprise-edition/content-collections/application-security/visibility/sbom/sbom.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-36651
Test URLs:
=> [CAS] SBOM Added JS and Python frameworks for AI/ML libraries

docs/en/compute-edition/32/admin-guide/authentication/user-roles.adoc, docs/en/compute-edition/32/admin-guide/book.yml, docs/en/compute-edition/32/admin-guide/install/deploy-defender/orchestrator/orchestrator.adoc
Fix: This is a PR for AG updates in PCCE
- https://redlock.atlassian.net/browse/CWP-51370
Test URLs:
=> [Runtime Security] AG - PCCE O'Neal Update 7

docs/api/_build/src/gen_supported_spec_saas.py, docs/api/_build/src/gen_supported_spec_sh.py, docs/api/descriptions/agentless/agentless.md, docs/api/descriptions/audits/audits.md, docs/api/descriptions/certs/certs.md, docs/api/descriptions/containers/download_get.md, docs/api/descriptions/registry/get_registry_progress.md, docs/api/descriptions/vms/vms.md, docs/en/compute-edition/32/admin-guide/configure/disaster-recovery.adoc, docs/en/compute-edition/32/admin-guide/vulnerability-management/cvss-scoring.adoc, docs/en/compute-edition/32/admin-guide/vulnerability-management/scan-reports.adoc, docs/en/enterprise-edition/content-collections/runtime-security/configure/disaster-recovery.adoc, docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/cvss-scoring.adoc, docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/scan-reports.adoc
Changes are done for tickets - https://redlock.atlassian.net/browse/CWP-58647, https://redlock.atlassian.net/browse/CWP-57289, https://redlock.atlassian.net/browse/CWP-57722 and https://redlock.atlassian.net/browse/CWP-58672
=> API improvement- set2 - Authentication details deletion

docs/en/compute-edition/32/rn/book.yml, docs/en/compute-edition/32/rn/book_point_release.yml, docs/en/compute-edition/32/rn/release-information/release-notes-32-07.adoc
Fix : This is a fix for #763 
Test URLs:
=> [Runtime Security] Fix for RN PCCE

docs/en/enterprise-edition/content-collections/application-security/visibility/repositories.adoc
Jira ticket:https://redlock.atlassian.net/browse/BCE-36989
Test URLs:
=> [CAS] Repositories page Fix link to investigate queries

docs/en/enterprise-edition/content-collections/application-security/manage-network-tunnel/manage-network-tunnel.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-37070
Test URLs:
=> [CAS] Modify Transporter permissions

docs/en/enterprise-edition/content-collections/application-security/manage-network-tunnel/manage-network-tunnel.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-37053
Test URLs:
=> [CAS] Revised permissions for Transporter

docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/configure-accounts/configure-accounts.adoc
=> Update Azure and oci path

docs/en/enterprise-edition/content-collections/dashboards/dashboards-discovery-exposure-management.adoc
=> RLP-146546 - Note update to enable CDEM dashboard.

docs/en/compute-edition/32/rn/book.yml, docs/en/compute-edition/32/rn/release-information/known-issues-32.adoc, docs/en/compute-edition/32/rn/release-information/release-notes-32-06.adoc, docs/en/compute-edition/32/rn/release-information/release-notes-32-07.adoc, docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-july-2024.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-june-2024.adoc
Fix : As per the conversation with @manukumar6 on Slack/call.
Test URLs:
=> [Runtime Security] RN-Fix as per request

docs/en/enterprise-edition/content-collections/application-security/visibility/sbom/sbom.adoc, docs/en/enterprise-edition/content-collections/application-security/visibility/visibility.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-37211
Test URLs:
=> [CAS] SBOM Renamed the AISPM third party AI/ML section 

docs/en/enterprise-edition/content-collections/runtime-security/cloud-service-providers/cloud-service-providers.adoc
=> removed registry and image scanning support for Azure

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-july-2024.adoc
=> 7 3 updates

docs/en/enterprise-edition/content-collections/application-security/supported-technologies.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-37315
Test URLs:
=> [CAS] Added support for the Opentofu IaC framework

docs/en/enterprise-edition/policy-reference/docker-policies/docker-policy-index/ensure-docker-apt-is-not-used.adoc
The example was broken and the description was not clear as noted [here](https://github.com/bridgecrewio/checkov/issues/6567#issuecomment-2244604105).
=> Fix CKV_DOCKER_9 docs

docs/en/enterprise-edition/content-collections/governance/custom-build-policies/custom-build-policies.adoc, docs/en/enterprise-edition/content-collections/governance/custom-build-policies/custom-build-policy-examples.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-37258
Test URLs:
=> [Governance] Added blocklist example to custom build policy examples

docs/en/compute-edition/32/rn/release-information/release-information.adoc, docs/en/compute-edition/32/rn/release-information/release-notes-32-07.adoc, docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
Fix: This PR has a list of changes that include minor and major fixes:
1. Remove lead sentence for a list on the landing page of Compute RN. 
Test URLs:
=> [Runtime Security] Post O'Neal 7 Updates

docs/en/compute-edition/32/rn/release-information/known-issues-32.adoc, docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
Added a known issue that just came in CWP-61287 
Test URLs:
=> Update for CWP-61287

docs/en/compute-edition/32/admin-guide/book.yml, docs/en/compute-edition/32/admin-guide/vulnerability-management/cvss-scoring.adoc, docs/en/enterprise-edition/content-collections/book.yml, docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/cvss-scoring.adoc, docs/en/enterprise-edition/content-collections/runtime-security/waas/deploy-waas/vpc-mirroring.adoc
=> Update broken links in WAAS adocs

docs/en/enterprise-edition/content-collections/runtime-security/deployment-patterns/performance-planning.adoc
Update for CWP-61360
Test URLs:
=> Update for CWP-61360

docs/en/compute-edition/32/rn/release-information/known-issues-32.adoc, docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
Updated the known issues pages to remove CWP-61287 as it has been resolved
Test URLs:
=> CWP-61287 resolved

docs/en/enterprise-edition/content-collections/data-security-posture-management/api-documentation/authenticate-and-call-your-first-api.adoc, docs/en/enterprise-edition/content-collections/data-security-posture-management/data-security-posture-management.adoc, docs/en/enterprise-edition/content-collections/data-security-posture-management/troubleshooting/gcp-monitoring-issues.adoc, docs/en/enterprise-edition/content-collections/data-security-posture-management/welcome-to-prisma-cloud-aispm/introduction-ai.adoc, docs/en/enterprise-edition/content-collections/data-security-posture-management/welcome/platform-overview/platform-overview.adoc
=> [DSPM] Fixed broken links

docs/en/enterprise-edition/content-collections/book.yml, docs/en/enterprise-edition/content-collections/data-security-posture-management/data-security-posture-management.adoc
Remove the welcome/intro page and move the content (driven by a Gdoc) to `data-security-posture-management/data-security-posture-management`
=> [Dig docs] Refactor intro

docs/en/enterprise-edition/content-collections/book.yml, docs/en/enterprise-edition/content-collections/data-security-posture-management/welcome/platform-overview/data-types.adoc
From:
Welcome > Platform Overview > Entities
To:
Welcome > Platform Overview > Data Types
=> [Dig docs] Update article title

docs/en/enterprise-edition/content-collections/book.yml, docs/en/enterprise-edition/content-collections/data-security-posture-management/prisma-cloud-dspm-integrations/integrate-dig-security-with-wiz.adoc
=> [Dig docs] Remove article

docs/en/compute-edition/32/admin-guide/install/deploy-defender/deploy-defender.adoc, docs/en/compute-edition/32/rn/release-information/release-notes-32-07.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/deploy-defender/deploy-defender.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-july-2024.adoc
=> content for PCSUP-23319

docs/en/enterprise-edition/content-collections/search-and-investigate/launch-your-query.adoc, docs/en/enterprise-edition/content-collections/search-and-investigate/permissions-queries/permissions-query-attributes.adoc
=> CSPM-8-1-Updates

docs/en/compute-edition/32/admin-guide/install/deploy-defender/deploy-defender.adoc
=> updated image paths

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
=> 8-1-RN-Update

docs/en/enterprise-edition/content-collections/alerts/prisma-cloud-alert-resolution-reasons.adoc, docs/en/enterprise-edition/content-collections/search-and-investigate/permissions-queries/permissions-query-attributes.adoc
=> PCEE-Updates 

docs/en/compute-edition/32/admin-guide/install/system-requirements.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/system-requirements.adoc
=> PCSUP-23758

docs/en/enterprise-edition/content-collections/data-security-posture-management/welcome/use-cases.adoc
=> [dig-docs] Updated use cases document

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-august-2024.adoc
=> [8.1 RN] Late Updates

docs/en/enterprise-edition/content-collections/application-security/visibility/repositories.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-37921
Test URLs:
=> [CAS] Repositories - Removed link

docs/en/compute-edition/32/rn/release-information/known-issues-32.adoc, docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
Fix:
- https://redlock.atlassian.net/browse/CWP-59435
Test URLs:
=> [Runtime Security] Add Known Issue - O'Neal Update 7

docs/en/enterprise-edition/content-collections/application-security/manage-network-tunnel/manage-network-tunnel.adoc
=> [App Sec] Fix link to Cloud Sec topic

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
=> [CSPM] Known Issue

docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-github-actions.adoc
Jira ticker: https://redlock.atlassian.net/browse/BCE-37993
Test URLs:
=> [CAS] GitHub Actions: Added config examples link to GitHub Actions job

docs/en/enterprise-edition/rn/limited-ga-features-prisma-cloud/limited-ga-features-prisma-cloud.adoc
=> [LGA] Remove DSPM 8.1

docs/en/enterprise-edition/content-collections/administration/define-prisma-cloud-enterprise-settings.adoc, docs/en/enterprise-edition/content-collections/administration/setup-sso-integration-on-prisma-cloud/get-started-with-saml-sso/setup-sso-integration-on-prisma-cloud-for-microsoft-azure-active-directory.adoc
=> minor-fixes

docs/api/_topic_map.yml
=> Set Serverless Runtime Policy changes - CWP-61497

docs/en/enterprise-edition/content-collections/runtime-security/compliance/operations/detect-secrets.adoc
=> Updated for CWP-61555

docs/en/enterprise-edition/content-collections/book.yml, docs/en/enterprise-edition/content-collections/data-security-posture-management/prisma-cloud-dspm-integrations/dspm-wildfire-integration-guide.adoc
- I added a new procedure: Integrating Prisma DSPM with Wildfire
- Updated several articles.
- Pushed all the links in 69 of Docs Issues
=> [Dig Security] Updates

docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-jenkins.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-38229
Test URLs:
=> [CAS] Jenkins Integration. Added example of how to Integrate Checkov into Jenkins Maven jobs

docs/en/compute-edition/32/rn/release-information/release-notes-32-00.adoc, docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/configure-accounts/configure-azure.adoc, docs/en/enterprise-edition/content-collections/runtime-security/cloud-service-providers/cloud-discovery.adoc, docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/scan-reports.adoc
=> [PCSUPs] RN, Runtime topics

docs/en/enterprise-edition/content-collections/data-security-posture-management/welcome/supported-assets.adoc
Updated Supported Assets .adoc
=> [Dig Security] Updated Supported Assets

docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-jenkins.adoc
Jira ticket: https://redlock.atlassian.net/browse/BCE-38229
Test URLs:
=> [CAS Jenkins freestyle projects usage

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
=> Pascal (33.00) Look Ahead 

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
=> added all LA tickets

docs/en/enterprise-edition/use-cases/book.yml, docs/en/enterprise-edition/use-cases/secure-the-infrastructure/onboard-aws-delegated-member-accounts.adoc
=> RLP-147299

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
=> changed the URL

docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-august-2024.adoc
=> [Cloud Sec] C2C Text Update

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
Adding a recently identified issue for which a fix will be provided in the upcoming release. 
Test URLs:
=> Update for CWP-61752

docs/en/compute-edition/32/admin-guide/install/system-requirements.adoc, docs/en/enterprise-edition/content-collections/administration/configure-iam-security/integrate-prisma-cloud-with-okta.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/system-requirements.adoc
=> Defenders CPU - Customer Issue

docs/en/compute-edition/33/rn/book.yml, docs/en/compute-edition/33/rn/book_point_release.yml, docs/en/compute-edition/33/rn/release-information/known-issues-33.adoc, docs/en/compute-edition/33/rn/release-information/release-notes-33-00.adoc
=> [Runtime Security] PCCE RN- Pascal

docs/en/compute-edition/33/admin-guide/agentless-scanning/onboard-accounts/configure-aws.adoc, docs/en/compute-edition/33/admin-guide/agentless-scanning/onboard-accounts/configure-gcp.adoc, docs/en/compute-edition/33/admin-guide/configure/configure-scan-intervals.adoc, docs/en/compute-edition/33/admin-guide/configure/permissions.adoc, docs/en/compute-edition/33/admin-guide/runtime-defense/custom-runtime-rules.adoc, docs/en/compute-edition/33/admin-guide/vulnerability-management/registry-scanning/configure-registry-scanning.adoc
=> CWP-59114 CWP-61459 CWP-58230 CWP-57290 CWP-61693

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-september-2024.adoc
=> [Runtime Security] RN-PCEE (Pascal)

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
Removed CWP-61752 as it is fixed
Test URLs:
=> Removed CWP-61752

docs/en/compute-edition/33/admin-guide/install/system-requirements.adoc
Fixing the link for the system-requirements sheet
Test URLs:
=> Fixing the link for the system-requirements sheet

docs/en/enterprise-edition/content-collections/runtime-security/install/system-requirements.adoc
=> Update enterprise edition system-requirements.adoc

docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/configure-accounts/configure-aws.adoc, docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/configure-accounts/configure-gcp.adoc, docs/en/enterprise-edition/content-collections/runtime-security/configure/configure-scan-intervals.adoc, docs/en/enterprise-edition/content-collections/runtime-security/configure/permissions.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/system-requirements.adoc, docs/en/enterprise-edition/content-collections/runtime-security/runtime-defense/custom-runtime-rules.adoc, docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/registry-scanning/configure-registry-scanning.adoc
=> Pascal changes for Enterprise edition

docs/en/enterprise-edition/content-collections/application-security/supported-technologies.adoc
Jira ticket:https://redlock.atlassian.net/browse/BCE-39232
Test URLs:
=> [CAS] Supported Frameworks limitations for Gradle and Maven multi-module projects

docs/en/compute-edition/33/rn/release-information/release-notes-33-00.adoc
Fix: Further to the exit letter, this change has the updated SHA number required for PCCE RN- Pascal
Test URLs:
=> [Runtime Security] PCCE-RN Update

docs/en/compute-edition/33/admin-guide/upgrade/support-lifecycle.adoc
=> support lifecycle for 33.xx

docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-gcp/prerequisites-to-onboard-gcp.adoc, docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-september-2024.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/prisma-cloud-release-info.adoc
=> [CSPM RN] 9.2 release.

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
Fix 
CWP-32911 
CWP-58952 
CWP-59654 
CWP-61840   
CWP-61917
Test URLs:
=> Look Ahead for Pascal Update 1

docs/en/enterprise-edition/policy-reference/alibaba-policies/alibaba-networking-policies/ensure-alibaba-cloud-alb-acl-restricts-public-access.adoc, docs/en/enterprise-edition/policy-reference/alibaba-policies/alibaba-networking-policies/ensure-alibaba-cloud-cypher-policy-is-secured.adoc, docs/en/enterprise-edition/policy-reference/aws-policies/aws-general-policies/ensure-aws-appsync-api-cache-is-encrypted-at-rest.adoc, docs/en/enterprise-edition/policy-reference/aws-policies/aws-general-policies/ensure-aws-elasticsearch-domain-uses-an-updated-tls-policy.adoc, docs/en/enterprise-edition/policy-reference/azure-policies/azure-networking-policies/ensure-azure-spring-cloud-api-portal-is-enabled-for-https.adoc, docs/en/enterprise-edition/policy-reference/azure-policies/azure-networking-policies/ensure-azure-spring-cloud-api-portal-public-access-is-disabled.adoc, docs/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/ensure-that-the-event-qps-argument-is-set-to-0-or-a-level-which-ensures-appropriate-event-capture.adoc, docs/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/ensure-that-the-kubelet-only-makes-use-of-strong-cryptographic-ciphers.adoc, docs/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/ensure-that-the-rotate-certificates-argument-is-not-set-to-false.adoc, docs/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/ensure-that-the-rotatekubeletservercertificate-argument-is-set-to-true-for-controller-manager.adoc, docs/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/granting-create-permissions-to-nodesproxy-or-podsexec-sub-resources-allows-potential-privilege-escalation.adoc, docs/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/no-serviceaccountnode-should-be-able-to-read-all-secrets.adoc, docs/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/no-serviceaccountnode-should-have-impersonate-permissions-for-groupsusersservice-accounts.adoc, docs/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/rolebinding-should-not-allow-privilege-escalation-to-a-serviceaccount-or-node-on-other-rolebinding.adoc, docs/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/serviceaccounts-and-nodes-potentially-exposed-to-cve-2020-8554.adoc
=> Fix formats for scraper 

docs/en/enterprise-edition/content-collections/alerts/view-respond-to-prisma-cloud-alerts.adoc, docs/en/enterprise-edition/content-collections/governance/create-a-policy.adoc, docs/en/enterprise-edition/rn/limited-ga-features-prisma-cloud/limited-ga-features-prisma-cloud.adoc, docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
=> Post 9.2 doc fixes 

docs/en/enterprise-edition/policy-reference/book.yml, docs/en/enterprise-edition/policy-reference/ibm-policies/ibm-general-policies/bc-ibm-2-1.adoc, docs/en/enterprise-edition/policy-reference/ibm-policies/ibm-general-policies/bc-ibm-2-2.adoc, docs/en/enterprise-edition/policy-reference/ibm-policies/ibm-general-policies/ibm-general-policies.adoc, docs/en/enterprise-edition/policy-reference/ibm-policies/ibm-iam-policies/bc-ibm-2-3.adoc, docs/en/enterprise-edition/policy-reference/ibm-policies/ibm-iam-policies/bc-ibm-2-4.adoc, docs/en/enterprise-edition/policy-reference/ibm-policies/ibm-iam-policies/bc-ibm-2-5.adoc, docs/en/enterprise-edition/policy-reference/ibm-policies/ibm-iam-policies/ibm-iam-policies.adoc, docs/en/enterprise-edition/policy-reference/ibm-policies/ibm-networking-policies/bc-ibm-2-7.adoc, docs/en/enterprise-edition/policy-reference/ibm-policies/ibm-networking-policies/ibm-networking-policies.adoc, docs/en/enterprise-edition/policy-reference/ibm-policies/ibm-policies.adoc
Replaces https://github.com/hlxsites/prisma-cloud-docs/pull/800
Test URLs:
=> IBM Build Policies take 2

docs/en/enterprise-edition/content-collections/application-security/get-started/application-security-settings/application-security-settings.adoc
The titles of the settings were swapped
=> Switch titles for secrets settings

docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/scan-reports.adoc
=> [Runtime] Added Note under host-and-vm-image-scanning

docs/en/enterprise-edition/content-collections/administration/network-security/container-network-exposure/satellite-permissions.adoc, docs/en/enterprise-edition/content-collections/prisma-cloud-copilot/prisma-cloud-copilot.adoc, docs/en/enterprise-edition/content-collections/search-and-investigate/application-queries/application-queries.adoc, docs/en/enterprise-edition/content-collections/search-and-investigate/permissions-queries/permissions-query-attributes.adoc, docs/en/enterprise-edition/content-collections/search-and-investigate/search-and-investigate.adoc
=> [24.10.1] Minor Updates

docs/en/compute-edition/33/admin-guide/install/system-requirements.adoc, docs/en/compute-edition/33/rn/book.yml, docs/en/compute-edition/33/rn/book_point_release.yml, docs/en/compute-edition/33/rn/release-information/known-issues-33.adoc, docs/en/compute-edition/33/rn/release-information/release-notes-33-01.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/system-requirements.adoc, docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-october-2024.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-september-2024.adoc
=> Update to the 33.01 RN

docs/en/compute-edition/33/admin-guide/install/deploy-defender/container/container.adoc, docs/en/compute-edition/33/admin-guide/install/deploy-defender/defender-types.adoc, docs/en/compute-edition/33/admin-guide/install/deploy-defender/host/windows-host.adoc, docs/en/compute-edition/33/admin-guide/technology-overviews/defender-architecture.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/deploy-defender/container/container.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/deploy-defender/defender-architecture.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/deploy-defender/defender-types.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/deploy-defender/host/windows-host.adoc
=> Podman updates (CWP-61840)

docs/en/compute-edition/32/admin-guide/welcome/utilities-and-plugins.adoc, docs/en/compute-edition/33/admin-guide/welcome/utilities-and-plugins.adoc, docs/en/enterprise-edition/content-collections/runtime-security/runtime-security-components/utilities-and-plugins.adoc
=> Utilities & Plugins topic

docs/en/compute-edition/33/rn/release-information/known-issues-33.adoc, docs/en/compute-edition/33/rn/release-information/release-notes-33-01.adoc, docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
=> rewrote CWP-61606 and added SHA for PCCE

docs/en/compute-edition/33/admin-guide/welcome/releases.adoc, docs/en/compute-edition/33/admin-guide/welcome/security-assurance-policy.adoc, docs/en/enterprise-edition/content-collections/runtime-security/runtime-defense/runtime-audits.adoc
=> Fix issues in the Compute admin guide

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
=> [Known Issue] Added RLP-152263

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
=> CWP-61660 - Additional reserved Ingress IP addresses

docs/en/enterprise-edition/content-collections/governance/custom-build-policies/custom-build-policy-examples.adoc, docs/en/enterprise-edition/content-collections/governance/custom-build-policies/visual-editor.adoc
=> Improve Build Editor docs

docs/en/enterprise-edition/rn/limited-ga-features-prisma-cloud/limited-ga-features-prisma-cloud.adoc
=> [LGA] RLP-152449

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc, docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
=> 10.1 la update

docs/en/enterprise-edition/content-collections/search-and-investigate/permissions-queries/permissions-query-attributes.adoc, docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
=> 10-1-updates

docs/en/compute-edition/22-12/admin-guide/runtime-defense/incident-types/others.adoc, docs/en/compute-edition/30/admin-guide/runtime-defense/incident-types/others.adoc, docs/en/compute-edition/31/admin-guide/runtime-defense/incident-types/others.adoc, docs/en/compute-edition/32/admin-guide/runtime-defense/incident-types/others.adoc, docs/en/compute-edition/33/admin-guide/runtime-defense/incident-types/others.adoc, docs/en/enterprise-edition/content-collections/runtime-security/runtime-defense/incident-types/others.adoc
=> [Runtime & Compute] PCSUP-24360, CWP-61990

docs/en/enterprise-edition/content-collections/book.yml, docs/en/enterprise-edition/content-collections/prisma-cloud-copilot/collection-prisma-cloud-copilot.yml, docs/en/enterprise-edition/content-collections/prisma-cloud-copilot/prisma-cloud-copilot-rql.adoc, docs/en/enterprise-edition/content-collections/prisma-cloud-copilot/prisma-cloud-copilot.adoc
=> [PC Copilot] Add RQL Examples

docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-aws/onboard-aws-account.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-aws/onboard-aws-org.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-gcp/onboard-gcp-org.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-gcp/onboard-gcp-project.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-gcp/onboard-gcp-workspace.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-alibaba-account/add-alibaba-cloud-account-to-prisma-cloud.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/connect-azure-active-directory.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/connect-azure-subscription.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/connect-azure-tenant.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-oci-account/add-oci-tenant-to-prisma-cloud.adoc
=> RLP-149985

docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-november-2024.adoc
=> 11-1-link-fix

docs/en/enterprise-edition/policy-reference/book.yml, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-120.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-146.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-166.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-168.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-171.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-175.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-177.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-178.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-180.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-184.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-185.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-191.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-192.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-220.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-223.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-226.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-240.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-242.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-244.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-248.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-254.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/git-secrets-256.adoc, docs/en/enterprise-edition/policy-reference/secrets-policies/secrets-policy-index/secrets-policy-index.adoc
=> Add new secrets for November release

docs/en/enterprise-edition/policy-reference/oci-policies/networking/bc-oci-21.adoc
Fix https://github.com/bridgecrewio/checkov/issues/6745
Test URLs:
=> Fix CKV_OCI_21

docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-gcp/prerequisites-to-onboard-gcp.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-august-2024.adoc
Azure ingestion permission update based on RLP-152514
Test URLs:
=> [CSPM RN] post-rn-11-1 requests

docs/en/enterprise-edition/policy-reference/azure-policies/azure-kubernetes-policies/azr-kubernetes-169.adoc
=> Update AKS check fix

docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-november-2024.adoc
=> [24.11.1] Late updates

docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-november-2024.adoc
=> CSPM RN API updates

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
=> Additional IP addresses added to the cwp look ahead

docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-november-2024.adoc
=> [11.1 RN] Ingestions

docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-aws/aws-apis-ingested-by-prisma-cloud.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-gcp/gcp-apis-ingested-by-prisma-cloud.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-alibaba-account/alibaba-apis-ingested-by-prisma-cloud.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/microsoft-azure-apis-ingested-by-prisma-cloud.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-oci-account/oci-apis-ingested-by-prisma-cloud.adoc
=> [API Ingestions] text update

docs/en/enterprise-edition/content-collections/governance/custom-build-policies/custom-build-policies.adoc
=> Adjust language for secrets custom policies

docs/en/enterprise-edition/content-collections/application-security/ides/connect-jetbrains.adoc, docs/en/enterprise-edition/content-collections/application-security/ides/connect-vscode.adoc
https://jira-dc.paloaltonetworks.com/browse/BCE-41357
Test URLs:
=> [CAS} Fix IDE docs

docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-gitlab-selfmanaged.adoc
https://jira-dc.paloaltonetworks.com/browse/BCE-41364
Test URLs:
=> [CAS] GitLab self-managed- add requirement

docs/en/enterprise-edition/content-collections/application-security/get-started/non-default-branch-scan.adoc
Jira: https://jira-dc.paloaltonetworks.com/browse/BCE-41415
Test URLs:
=> [CAS] Limit non-default branch scans to developer-based billing

docs/api/_topic_map.yml, docs/api/descriptions/sbom/download_ci_images_get.md, docs/api/descriptions/sbom/download_ci_serverless_get.md, docs/api/descriptions/sbom/download_cli_serverless_get.md
=> pascal-update2-api-ref changes

docs/en/compute-edition/33/rn/book.yml, docs/en/compute-edition/33/rn/book_point_release.yml, docs/en/compute-edition/33/rn/release-information/known-issues-33.adoc, docs/en/compute-edition/33/rn/release-information/release-notes-33-02.adoc, docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc, docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-november-2024.adoc
=> Pascal update-2 RN changes

docs/en/compute-edition/32/admin-guide/configure/certificates.adoc
=> Certificates table formatting 

docs/en/compute-edition/32/admin-guide/waas/deploy-waas/deployment-containers.adoc, docs/en/compute-edition/33/admin-guide/waas/deploy-waas/deployment-containers.adoc, docs/en/enterprise-edition/content-collections/runtime-security/waas/deploy-waas/containers.adoc
=> PCSUP-25007

docs/en/compute-edition/33/rn/book.yml, docs/en/compute-edition/33/rn/release-information/release-notes-33-02.adoc
=> Updated the on-prem RN with hotfix details

docs/en/compute-edition/33/admin-guide/technology-overviews/intel-stream.adoc, docs/en/enterprise-edition/content-collections/runtime-security/runtime-security-components/intelligence-stream.adoc
=> CWP-61917 - Multiple Intelligence Builders

docs/en/enterprise-edition/content-collections/administration/action-plans.adoc, docs/en/enterprise-edition/content-collections/administration/collection-administration.yml, docs/en/enterprise-edition/content-collections/book.yml
=> action-plans

docs/en/compute-edition/31/admin-guide/install/deploy-defender/host/host.adoc, docs/en/compute-edition/32/admin-guide/install/deploy-defender/host/host.adoc, docs/en/compute-edition/33/admin-guide/install/deploy-defender/host/host.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/deploy-defender/container/container.adoc
=> Updates for CWP-62517

docs/en/enterprise-edition/content-collections/book.yml, docs/en/enterprise-edition/content-collections/data-security-posture-management/prisma-cloud-dspm-deployment/deploy-prisma-cloud-dspm-on-aws/offboardaws.adoc
Rename article from "Offboarding AWS Organization" to "Offboarding AWS"
=> [DSPM] Rename article title

docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-gitlab-selfmanaged.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-gitlab.adoc
Jira ticket:https://jira-dc.paloaltonetworks.com/browse/BCE-42125
Test URLs:
=> [CAS] Onboarding GitLab. Modify integration permissions according to least privilege

docs/en/enterprise-edition/content-collections/administration/configure-iam-security/azure-cloud-identity-inventory.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-december-2024.adoc
=> Ciem updates

docs/en/compute-edition/30/admin-guide/install/deploy-console/console-on-kubernetes.adoc, docs/en/compute-edition/31/admin-guide/install/deploy-console/console-on-kubernetes.adoc, docs/en/compute-edition/32/admin-guide/install/deploy-console/console-on-kubernetes.adoc, docs/en/compute-edition/33/admin-guide/install/deploy-console/console-on-kubernetes.adoc
=> [Runtime] Install PC with Helm Charts

docs/en/enterprise-edition/content-collections/search-and-investigate/rql-operators.adoc
=> [Cloud Security-S&I] RQL Operators

docs/en/enterprise-edition/content-collections/application-security/ides/connect-vscode.adoc
=> [App Sec] Update python version

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
=> [CSPM RN] - 12.1 LA (25.1.1) Post publish updates 

docs/en/enterprise-edition/content-collections/book.yml, docs/en/enterprise-edition/content-collections/data-security-posture-management/prisma-cloud-dspm-deployment/prisma-cloud-dspm-deployment.adoc, docs/en/enterprise-edition/content-collections/data-security-posture-management/prisma-cloud-dspm-deployment/subscribe-dspm.adoc, docs/en/enterprise-edition/content-collections/data-security-posture-management/prisma-cloud-dspm-deployment/subscribe-prisma-cloud-dspm-within-dspm/subscribedspm.adoc
=> [DSPM] DIGX-3454: Subscribe to Prisma Cloud DSPM Within Prisma Cloud

docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-december-2024.adoc
=> [24.12.1 RN] Action Plans Rollout

docs/en/enterprise-edition/content-collections/administration/action-plans.adoc, docs/en/enterprise-edition/content-collections/administration/administration.adoc
=> action-plans-note

docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-checkov.adoc
=> metadata permissions exception

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
=> LA Pascal Update 3 (CWP-49786 and CWP-30827)

docs/en/enterprise-edition/content-collections/book.yml, docs/en/enterprise-edition/content-collections/data-security-posture-management/how-to-articles/explore-data-asset-access-information.adoc, docs/en/enterprise-edition/content-collections/data-security-posture-management/how-to-articles/how-to-articles.adoc, docs/en/enterprise-edition/content-collections/data-security-posture-management/how-to-articles/view-access-details-to-specific-storage-buckets.adoc
=> [DSPM] Title & URL update

docs/en/enterprise-edition/content-collections/book.yml, docs/en/enterprise-edition/content-collections/connect/collection-connect.yml, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/connect-azure-active-directory.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/connect-azure-tenant.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/connect-microsoft-entra-id.adoc
=> [Cloud Sec] Azure AD PCSUP-24945

docs/en/enterprise-edition/rn/book.yml
=> corrected book info for enterprise edition

docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2025/features-introduced-in-2025.adoc
=> added landing file for 2025

docs/en/compute-edition/33/admin-guide/compliance/custom-compliance-checks.adoc, docs/en/enterprise-edition/content-collections/runtime-security/compliance/visibility/custom-compliance-checks.adoc
=> Update for CWP-53869

docs/en/compute-edition/33/rn/release-information/known-issues-33.adoc
=> Update to CWP RN for PCSUP-26234

docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-amazon-guardduty.adoc
=> [PCSUP] Doc Fixes Dec 2024

docs/en/enterprise-edition/content-collections/administration/configure-iam-security/context-used-to-calculate-effective-permissions.adoc, docs/en/enterprise-edition/content-collections/search-and-investigate/permissions-queries/permissions-query-attributes.adoc
=> 1-1-updates

docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/add-notification-template.adoc, docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-qualys.adoc, docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-servicenow.adoc, docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
This PR includes two minor CSPM Content collection updates for SNOW and Qualys integrations. Please take a look at Commits for more details.
Test URLs:
=> [CSPM RN] 25.1.1: Post publish updates for LA

docs/en/enterprise-edition/content-collections/book.yml, docs/en/enterprise-edition/content-collections/data-security-posture-management/prisma-cloud-dspm-deployment/deploy-prisma-cloud-dspm-on-gcp/deploy-prisma-cloud-dspm-on-gcp.adoc, docs/en/enterprise-edition/content-collections/data-security-posture-management/prisma-cloud-dspm-deployment/deploy-prisma-cloud-dspm-on-gcp/offboarding-gcp.adoc
=> [DSPM] Add GCP Offboarding topic

docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2025/features-introduced-in-january-2025.adoc
=> [25.1.1 RN] DSPM update - Changes in Existing Behavior

docs/en/enterprise-edition/content-collections/administration/network-security/container-network-exposure/satellite-permissions.adoc
=> Updated for task-kubeapi-role

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
=> LA 25.2.1 - Config Policies update

docs/en/enterprise-edition/.vscode/settings.json, docs/en/enterprise-edition/content-collections/application-security/collection-application-security.yml, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/connect-code-and-build-providers.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/veracode-ingestion.adoc, docs/en/enterprise-edition/content-collections/book.yml
https://jira-dc.paloaltonetworks.com/browse/BCE-40803
Test URLs:
=> [CAS] Veracode SAST ingestion

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
=> PCSUP-26850

docs/en/compute-edition/33/admin-guide/runtime-defense/runtime-defense-containers.adoc
=> [Runtime] PCSUP-10244 content enhancement

docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-gcp/prerequisites-to-onboard-gcp.adoc, docs/en/enterprise-edition/rn/book.yml, docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2025/features-introduced-in-2025.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2025/features-introduced-in-february-2025.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/prisma-cloud-release-info.adoc
This branch contains PC1 RN updates for Feb 2025.
Test URLs:
=> [CSPM RN] PCS 25-2-1

docs/en/enterprise-edition/content-collections/get-started/get-going.adoc, docs/en/enterprise-edition/rn/book.yml, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2025/features-introduced-in-february-2025.adoc
=> RN book and text fixes

docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-bitbucket.adoc
Jira ticket:https://jira-dc.paloaltonetworks.com/browse/BCE-44993
Test URLs:
=> [CAS] Bitbucket Cloud onboarding - expanded explanation for admin repo permissions

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc, docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
=> [25.2.1] Late updates

docs/en/compute-edition/32/admin-guide/book.yml, docs/en/compute-edition/33/admin-guide/book.yml
=> update book.yml file for file deletion

docs/en/compute-edition/33/admin-guide/book.yml, docs/en/enterprise-edition/content-collections/book.yml
=> delete files reference for CWP-61492

docs/en/compute-edition/33/rn/release-information/known-issues-33.adoc, docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
=> added a known issue - CWP-62780

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc, docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
=> [CSPM RN] Post 25-2-1 publish RN updates

docs/en/enterprise-edition/content-collections/administration/action-plans.adoc, docs/en/enterprise-edition/content-collections/administration/anomalies/anomalies-trusted-ip-addresses-on-prisma-cloud.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2025/features-introduced-in-february-2025.adoc
=> action-plans-update

docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2025/features-introduced-in-february-2025.adoc
=> rn-iam-fix

docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-terraform-enterprise-run-tasks.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-terraform-run-tasks.adoc
Updates the required permissions for run tasks, based on this ticket: https://jira-dc.paloaltonetworks.com/browse/PCSUP-26671
https://docs.prismacloud.io/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-terraform-run-tasks
https://docs.prismacloud.io/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-terraform-enterprise-run-tasks
=> update run task permissions

docs/en/enterprise-edition/content-collections/get-started/access-prisma-cloud.adoc, docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/configure-accounts/configure-azure.adoc
=> slack-fixes

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
=> [KI] PCSUP-26700

docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/vulnerability-explorer.adoc
=> [Runtime] Fix link

docs/en/enterprise-edition/policy-reference/google-cloud-policies/google-cloud-iam-policies/bc-gcp-iam-5.adoc, docs/en/enterprise-edition/policy-reference/google-cloud-policies/google-cloud-iam-policies/bc-gcp-iam-6.adoc
Update based on https://github.com/bridgecrewio/checkov/pull/6725
=> Update service account roles

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
=> rn-3-1-fix

docs/en/enterprise-edition/content-collections/cloud-and-software-inventory/applications-inventory.adoc
A note has been added based on https://jira-dc.paloaltonetworks.com/browse/RLP-155611
Test URLs:
=> [CSPM Content Collections] Update for Applications Inventory.

docs/api/descriptions/images/download_get.md, docs/en/compute-edition/34/admin-guide/install/deploy-defender/host/windows-host.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/deploy-defender/host/windows-host.adoc
=> AG + API changes for Quinn

docs/en/enterprise-edition/rn/limited-ga-features-prisma-cloud/limited-ga-features-prisma-cloud.adoc
=> [LGA Update] PCS 5089

docs/en/compute-edition/33/admin-guide/install/deploy-console/console-on-ack.adoc, docs/en/compute-edition/33/admin-guide/install/deploy-console/console-on-acs.adoc, docs/en/compute-edition/34/admin-guide/install/deploy-console/console-on-ack.adoc, docs/en/compute-edition/34/admin-guide/install/deploy-console/console-on-acs.adoc, docs/en/compute-edition/34/admin-guide/install/deploy-console/console-on-iks.adoc, docs/en/compute-edition/34/admin-guide/install/system-requirements.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/system-requirements.adoc
=> Pending updates for quinn

docs/en/compute-edition/34/rn/release-information/known-issues-34.adoc, docs/en/compute-edition/34/rn/release-information/release-notes-34-00.adoc
=> Quinn On-prem release notes

docs/en/compute-edition/33/admin-guide/configure/disaster-recovery.adoc, docs/en/compute-edition/34/admin-guide/authentication/oauth2-github.adoc, docs/en/compute-edition/34/admin-guide/authentication/oauth2-openshift.adoc, docs/en/compute-edition/34/admin-guide/authentication/saml-active-directory-federation-services.adoc, docs/en/compute-edition/34/admin-guide/authentication/saml-azure-active-directory.adoc, docs/en/compute-edition/34/admin-guide/authentication/saml-google-g-suite.adoc, docs/en/compute-edition/34/admin-guide/authentication/saml-ping-federate.adoc, docs/en/compute-edition/34/admin-guide/authentication/saml.adoc, docs/en/compute-edition/34/admin-guide/configure/collections.adoc, docs/en/compute-edition/34/admin-guide/configure/disaster-recovery.adoc, docs/en/compute-edition/34/admin-guide/vulnerability-management/serverless-functions.adoc, docs/en/compute-edition/34/admin-guide/vulnerability-management/vuln-management-rules.adoc, docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/agentless-scanning.adoc
=> Updates for CWP-59656

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
=> Quinn PCEE RN

docs/en/compute-edition/32/admin-guide/authentication/credentials-store/credentials-store.adoc, docs/en/compute-edition/33/admin-guide/authentication/credentials-store/credentials-store.adoc, docs/en/compute-edition/34/admin-guide/authentication/credentials-store/credentials-store.adoc, docs/en/enterprise-edition/content-collections/runtime-security/authentication/credentials-store/credentials-store.adoc, docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
=> rewrote the topics for CWP-62089

docs/en/compute-edition/34/rn/release-information/release-notes-34-00.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2025/features-introduced-in-march-2025.adoc
=> RN updates for CWP-63063 and CWP-62948

docs/en/compute-edition/32/admin-guide/install/deploy-defender/host/windows-host.adoc, docs/en/compute-edition/33/admin-guide/install/deploy-defender/host/windows-host.adoc, docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
=> CWP-59305 32 and 33 updates

.github/pull_request_template.md, README.md, bin/generate-sitemaps.js, bin/preview-changes.js, preview/README.md, wrangler.toml
Reverts hlxsites/prisma-cloud-docs#1078
=> Revert "feat: upgrade to v5"

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
=> [Known Issues] Update for PCS-5228

.github/pull_request_template.md, README.md, bin/generate-sitemaps.js, bin/preview-changes.js, preview/README.md, wrangler.toml
Reverts hlxsites/prisma-cloud-docs#1129
=> Revert "Revert "feat: upgrade to v5""

docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc, docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
=> 3-1-la-update

docs/en/enterprise-edition/content-collections/get-started/welcome-to-prisma-cloud.adoc
=> [Cloud Sec] License Update

docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-aws/configure-audit-logs.adoc
=> [Cloud Security] RLP-154635 EAI

docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-checkov.adoc
=> Update Checkov doc for proxy settings

docs/en/enterprise-edition/content-collections/application-security/collection-application-security.yml, docs/en/enterprise-edition/content-collections/application-security/get-started/add-pre-commit-hooks.adoc, docs/en/enterprise-edition/content-collections/application-security/get-started/add-pre-receive-hooks.adoc, docs/en/enterprise-edition/content-collections/book.yml
=> Add pre-commit hook docs

docs/en/enterprise-edition/policy-reference/docker-policies/docker-policy-index/bc-docker-2-17.adoc, docs/en/enterprise-edition/policy-reference/docker-policies/docker-policy-index/ensure-docker-apt-is-not-used.adoc, docs/en/enterprise-edition/policy-reference/docker-policies/docker-policy-index/ensure-docker-from-alias-is-unique-for-multistage-builds.adoc, docs/en/enterprise-edition/policy-reference/docker-policies/docker-policy-index/ensure-docker-workdir-values-are-absolute-paths.adoc, docs/en/enterprise-edition/policy-reference/docker-policies/docker-policy-index/ensure-that-copy-is-used-instead-of-add-in-dockerfiles.adoc, docs/en/enterprise-edition/policy-reference/docker-policies/docker-policy-index/ensure-that-healthcheck-instructions-have-been-added-to-container-images.adoc, docs/en/enterprise-edition/policy-reference/docker-policies/docker-policy-index/ensure-that-label-maintainer-is-used-instead-of-maintainer-deprecated.adoc, docs/en/enterprise-edition/policy-reference/docker-policies/docker-policy-index/ensure-the-base-image-uses-a-non-latest-version-tag.adoc, docs/en/enterprise-edition/policy-reference/docker-policies/docker-policy-index/ensure-update-instructions-are-not-used-alone-in-the-dockerfile.adoc
=> Docker doc fixes

docs/en/compute-edition/34/rn/release-information/release-notes-34-00.adoc
=> Input from Yaniv

docs/en/compute-edition/34/rn/release-information/known-issues-34.adoc, docs/en/compute-edition/34/rn/release-information/release-notes-34-00.adoc, docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2025/features-introduced-in-march-2025.adoc
=> Fixed minor formatting issues

docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-compute-release-information/features-introduced-in-compute-february-2024.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-september-2024.adoc
Fix the adoc syntax so that panconv can generate the correct DITA output for the Enterprise Edition release notes
=> Fix adoc syntax to generate dita correctly

docs/en/compute-edition/34/rn/release-information/release-notes-34-00.adoc
=> Fixed release date

docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2025/features-introduced-in-march-2025.adoc
=> [25.3.1] Policy Updates Fix

docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-amazon-sqs.adoc, docs/en/enterprise-edition/content-collections/search-and-investigate/asset-config-queries/asset-config-query-attributes.adoc, docs/en/enterprise-edition/content-collections/search-and-investigate/asset-config-queries/asset-config-query-examples.adoc, docs/en/enterprise-edition/content-collections/search-and-investigate/rql-faqs.adoc, docs/en/enterprise-edition/content-collections/search-and-investigate/rql-operators.adoc
=> [S&I] RQL fixes

docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2025/look-ahead-secure-the-infrastructure.adoc
=> [CSPM RN] Post publish LA update that went with 25.4.1

docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2025/features-introduced-in-april-2025.adoc
=> PCSUP-27915

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
=> RLP-133585

docs/en/compute-edition/34/admin-guide/install/deploy-defender/app-embedded/app-embedded.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/deploy-defender/app-embedded/app-embedded.adoc
=> update for CWP-63229

docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2025/features-introduced-in-april-2025.adoc
=> pcsup-27915-reverse

docs/en/compute-edition/34/rn/release-information/known-issues-34.adoc
=> Fixed issue CWP-62961

docs/en/enterprise-edition/content-collections/administration/add-a-resource-list-on-prisma-cloud.adoc
=> pcsup-28133

docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2025/features-introduced-in-may-2025.adoc
=> Updates for 34.01

.gitignore, docs/.idea/.gitignore, docs/en/compute-edition/34/admin-guide/install/system-requirements.adoc, docs/en/compute-edition/34/rn/book.yml, docs/en/compute-edition/34/rn/release-information/release-notes-34-01.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/system-requirements.adoc
=> Quinn update1

docs/en/compute-edition/34/admin-guide/technology-overviews/radar.adoc, docs/en/compute-edition/34/admin-guide/vulnerability-management/scan-reports.adoc, docs/en/enterprise-edition/content-collections/runtime-security/runtime-security-components/radar.adoc, docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/scan-reports.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-compute-release-information/features-introduced-in-compute-april-2023.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2025/features-introduced-in-march-2025.adoc
Changes done for [CWP-62687](https://jira-dc.paloaltonetworks.com/browse/CWP-62687), [CWP-63066](https://jira-dc.paloaltonetworks.com/browse/CWP-63066), [CWP-63175](https://jira-dc.paloaltonetworks.com/browse/CWP-63175), [CWP-62696](https://jira-dc.paloaltonetworks.com/browse/CWP-62696)
=> Quinn update1 ag changes

docs/en/compute-edition/34/rn/release-information/release-notes-34-01.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2025/features-introduced-in-may-2025.adoc
=> Minor edits to the 34.01 RNs 

docs/en/enterprise-edition/content-collections/multitenant-management/multitenant-management-sso.adoc
=> mttm-sso-update

docs/en/enterprise-edition/content-collections/runtime-security/install/deploy-defender/kubernetes/kubernetes-cri.adoc
=> CWP-63652 updates

docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/connect-azure-account.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2025/features-introduced-in-may-2025.adoc
=> RLP-148946

docs/en/enterprise-edition/rn/book.yml, docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc, docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2025/features-introduced-in-2025.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2025/features-introduced-in-june-2025.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/prisma-cloud-release-info.adoc
=> [25.6.1] RN Updates

docs/en/compute-edition/32/admin-guide/runtime-defense/image-analysis-sandbox.adoc, docs/en/compute-edition/33/admin-guide/configure/collections.adoc, docs/en/compute-edition/33/admin-guide/runtime-defense/image-analysis-sandbox.adoc, docs/en/compute-edition/34/admin-guide/configure/collections.adoc, docs/en/compute-edition/34/admin-guide/runtime-defense/image-analysis-sandbox.adoc, docs/en/enterprise-edition/content-collections/runtime-security/configure/collections.adoc
=> Updates for PCSUPs

docs/en/enterprise-edition/content-collections/alerts/view-respond-to-prisma-cloud-alerts.adoc
=> [Alerts] Fixed formatting

docs/en/compute-edition/34/rn/book.yml, docs/en/compute-edition/34/rn/release-information/known-issues-34.adoc, docs/en/compute-edition/34/rn/release-information/release-notes-34-01-129.adoc, docs/en/compute-edition/34/rn/release-information/release-notes-34-01-132.adoc, docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
=> 34.01 hotfix for PCCE

docs/en/compute-edition/34/admin-guide/vulnerability-management/vm-image-scanning.adoc
=> Fix table formatting

docs/en/enterprise-edition/content-collections/data-security-posture-management/welcome/supported-assets.adoc
=> [DSPM] Supported Assets update

docs/en/enterprise-edition/content-collections/application-security/ides/ides.adoc
[BCE-49958](https://jira-dc.paloaltonetworks.com/browse/BCE-49958)
Test URLs:
=> [CAS] Supported Windows Terminals

docs/en/compute-edition/34/admin-guide/install/deploy-defender/container/container.adoc, docs/en/enterprise-edition/content-collections/runtime-security/install/deploy-defender/container/container.adoc
=> CWP-63652 update for EE file

docs/en/enterprise-edition/content-collections/get-started/console-prerequisites.adoc
=> PCSUP-28063 update

docs/en/enterprise-edition/content-collections/administration/configure-iam-security/enable-iam-security.adoc, docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/connect-azure-account.adoc
=>  RLP-156405

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
=> [25.7.1 RN] 8.1 LA late additions

docs/en/enterprise-edition/content-collections/governance/create-a-policy.adoc
=> [PCSUP-20252] Doc fix

docs/en/enterprise-edition/content-collections/data-security-posture-management/welcome/supported-assets.adoc
=> DSPM Supported Assets update

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
=> [25.8.1 LA] Change in existing behavior

docs/en/compute-edition/32/admin-guide/book.yml, docs/en/compute-edition/33/admin-guide/book.yml, docs/en/compute-edition/34/admin-guide/book.yml
=> 34.02 AG updates

docs/en/compute-edition/34/rn/release-information/known-issues-34.adoc, docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2025/features-introduced-in-august-2025.adoc
=> Late breaking updates and fixes to Quinn Update 2 RNs

docs/en/compute-edition/33/admin-guide/agentless-scanning/agentless-scanning.adoc, docs/en/compute-edition/34/admin-guide/agentless-scanning/agentless-scanning.adoc, docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/agentless-scanning.adoc
=> CWP-64065 changes

docs/en/enterprise-edition/rule-reference/ci-cd-security/artifact-integrity-validation/artifact-integrity-validation.adoc, docs/en/enterprise-edition/rule-reference/ci-cd-security/ci-cd-security.adoc, docs/en/enterprise-edition/rule-reference/ci-cd-security/credential-hygiene/credential-hygiene.adoc, docs/en/enterprise-edition/rule-reference/ci-cd-security/data-protection/data-protection.adoc, docs/en/enterprise-edition/rule-reference/ci-cd-security/dependency-chains/dependency-chains.adoc, docs/en/enterprise-edition/rule-reference/ci-cd-security/flow-control-mechanism/flow-control-mechanism.adoc, docs/en/enterprise-edition/rule-reference/ci-cd-security/identitiy-access-management/identitiy-access-management.adoc, docs/en/enterprise-edition/rule-reference/ci-cd-security/input-validation/input-validation.adoc, docs/en/enterprise-edition/rule-reference/ci-cd-security/logging-and-visibility/logging-and-visibility.adoc, docs/en/enterprise-edition/rule-reference/ci-cd-security/pipeline-based-access-controls/pipeline-based-access-controls.adoc, docs/en/enterprise-edition/rule-reference/ci-cd-security/ppe/ppe.adoc, docs/en/enterprise-edition/rule-reference/ci-cd-security/system-configurations/system-configurations.adoc, docs/en/enterprise-edition/rule-reference/ci-cd-security/third-party-services/third-party-services.adoc, docs/en/enterprise-edition/rule-reference/get-started/get-started.adoc, docs/en/enterprise-edition/rule-reference/iac-security/ai-and-machine-learning/ai-and-machine-learning.adoc, docs/en/enterprise-edition/rule-reference/iac-security/compute/compute.adoc, docs/en/enterprise-edition/rule-reference/iac-security/iac-security.adoc, docs/en/enterprise-edition/rule-reference/iac-security/iam/iam.adoc, docs/en/enterprise-edition/rule-reference/iac-security/logging/logging.adoc, docs/en/enterprise-edition/rule-reference/iac-security/monitoring/monitoring.adoc, docs/en/enterprise-edition/rule-reference/iac-security/networking/networking.adoc, docs/en/enterprise-edition/rule-reference/iac-security/public-exposure/public-exposure.adoc, docs/en/enterprise-edition/rule-reference/iac-security/storage/storage.adoc, docs/en/enterprise-edition/rule-reference/secrets-security/api-service-keys/api-service-keys.adoc, docs/en/enterprise-edition/rule-reference/secrets-security/authentication-authorization/authentication-authorization.adoc, docs/en/enterprise-edition/rule-reference/secrets-security/cloud-infrastructure/cloud-infrastructure.adoc, docs/en/enterprise-edition/rule-reference/secrets-security/database-data-store/database-data-store.adoc, docs/en/enterprise-edition/rule-reference/secrets-security/generic-high-entropy/generic-high-entropy.adoc, docs/en/enterprise-edition/rule-reference/secrets-security/secrets-security.adoc, docs/en/enterprise-edition/rule-reference/secrets-security/source-control-ci-cd/source-control-ci-cd.adoc
=> Policy Reference migration: write index files

docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
=> 9-1-release-announcement

docs/en/compute-edition/34/rn/release-information/known-issues-34.adoc, docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
=> Updated as per latest info on PCSUP-28876

docs/en/enterprise-edition/content-collections/data-security-posture-management/welcome/supported-assets.adoc
=> [DSPM] Supported Assets Note update

docs/en/enterprise-edition/rn/book.yml, docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2025/features-introduced-in-2025.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2025/features-introduced-in-october-2025.adoc, docs/en/enterprise-edition/rn/prisma-cloud-release-info/prisma-cloud-release-info.adoc
=> [CSPM RN] PCS 25-10-1
